Added conditionals to differentiate between che and CRW
eclipse-che/che-docs pull request #1072
Opened 2020-02-12 13:48 UTC by boczkowska

### What does this PR do?
Adds conditionals to differentiate between che and CRW - where default project name is mentioned.

We don't have an attribute for `che` and `codeready-workspaces` so I decided to use conditionals.

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/RHDEVDOCS-1548

2020-02-12 16:48 UTC, nickboldt commented on src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
> +time="2019-07-12T09:50:13Z" level=info msg="Updating eclipse-che CR with {prod} server URL: http://codeready-workspaces.apps.cluster-fre-f0a2.fre-f0a2.openshiftworkshop.com"
is this block really needed? If it's the same in upstream too, then you could probably just define a new variable called `{deployment-route}` and set it to `che-che` or `codeready-workspaces` based on value of `{project-context}` variable.

2020-02-12 16:48 UTC, nickboldt commented on src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
> +* Wait for the logs to show the message `{prod} is now available at:` followed by {prod-short} URL:
this line is the same in the che block above.

2020-02-12 16:49 UTC, nickboldt commented on src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
> +time="2019-07-12T09:50:13Z" level=info msg="Updating eclipse-che CR with version: 7.0.0-RC-2.0"
Should we maybe update this from 7.0.0 RC2 (about a year old) to a more current actual version, like 7.8.0? Or if this is a CRW version, then 2.0.0?

2020-02-12 16:50 UTC, nickboldt requested changes
see suggestions inline.

2020-02-17 11:09 UTC, themr0c requested changes

2020-02-17 11:09 UTC, themr0c commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
>  . Navigate to the {prod-short} cluster instance: `++http://++che-che.__<OPENSHIFT_APPS_URL>__`.
I believe this is exactly a case where the use of the {prod-url} attribute would  be beneficial. No conditional would be even necessary.

```suggestion
. Navigate to the {prod-short} cluster instance: `{prod-url}`.
```

2020-02-17 11:09 UTC, themr0c commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
>  . Navigate to the {prod-short} cluster instance. The domain is now prefixed with HTTPS and using _Let’s Encrypt_ ACME certificates: `++https://++che-che.__<OPENSHIFT_APPS_URL>__`.
Using the {prod-url} attribute is clearly not an option here. What about introducing and using a `{prod-url-secure}` attribute with value `++https://che-host:che-port++` ? NB: attributes are defined in `src/main/_config.yml `.

2020-02-17 11:09 UTC, themr0c commented on src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
> +ifeval::["{project-context}" == "che"]
If here only the logs are different, what about externalizing the logs in `include/examples/{project-context}something.log` instead of the ifs?

2020-02-18 21:36 UTC, nickboldt commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
>  . Navigate to the {prod-short} cluster instance: `++http://++che-che.__<OPENSHIFT_APPS_URL>__`.
👍

2020-02-20 08:41 UTC, boczkowska commented
@nickboldt @themr0c  Apparently, a lot of the content in the procedures was changed in https://github.com/eclipse/che-docs/pull/1063 (And I even reviewed it... :woman_facepalming: )

I added attributes where applicable though.

2020-02-24 17:04 UTC, closed without merging