Fixing typos in multiple docs and enhancing the oc procedure
eclipse-che/che-docs pull request #1073
Opened 2020-02-12 17:36 UTC by MichalMaler

Signed-off-by: Michal Maléř <mmaler@redhat.com>

Fixing typos in multiple docs and enhancing the oc procedure + proper markup

2020-02-13 14:38 UTC, yhontyk approved these changes
LGTM

2020-02-17 11:05 UTC, themr0c requested changes

2020-02-17 11:05 UTC, themr0c commented on src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
> +* For additional information about custom environment properties and how to define them in CheCluster Custom Resource, see link:https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/[
```suggestion
* For additional information about custom environment properties and how to define them in CheCluster Custom Resource, see link:{site-baseurl}/che-7/advanced-configuration-options/[Advanced configuration options].
```

2020-02-17 11:06 UTC, themr0c approved these changes

2020-02-17 11:06 UTC, merged