I1696 che ifeval application
eclipse-che/che-docs pull request #1139
Opened 2020-03-16 15:34 UTC by MichalMaler

Signed-off-by: Michal Maléř mmaler@redhat.com

A version of already accepted PR in the master branch.

Fixing a broken link.
Specifying the upstream content.
Adding information about mother assembly.
Adding the :page-liquid: attribute to assembly metadata

2020-03-16 16:12 UTC, yhontyk requested changes

2020-03-16 16:12 UTC, boczkowska commented on src/main/pages/che-7/administration-guide/con_database-setup.adoc
> +PostgreSQL database is used for persisting data about the state of {prod-short}. It contains information about the user accounts, workspaces, preferences, ssh keys, and so on.
"is used" by what or who?

Specify, e.g. Eclipse Che uses PostreSQL....

2020-03-16 16:12 UTC, boczkowska commented on src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
> +This strategy exposes the components to the outside world on the sub-paths of the default host of the cluster. It is similar to the single-host strategy. All the limitations and advantages of the sin
Do not hyphen.

2020-03-16 16:12 UTC, boczkowska commented on src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
> +This strategy is available on Kubernetes, but not on OpenShift. When it is used, all workspaces are deployed to sub-paths of the main {prod-short} server domain.
Do not hyphen.

2020-03-16 16:12 UTC, boczkowska commented on src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
> +== Use cases
I'm pretty sure I fixed this one... Don't forget to rebase from time to time so we don't do double work. :D

2020-03-16 16:12 UTC, boczkowska commented on src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
> +- sub-paths of mount volumes that reference user-defined PVCs are prefixed with `{workspace id}/{PVC name}`.
Do not hyphen. The rule of thumb is to not hyphen whenever you can (if it doesn't affect the meaning of the word or doesn't create ambiguity).

2020-03-17 08:45 UTC, yhontyk approved these changes

2020-03-17 09:27 UTC, MichalMaler commented
This has to be canceled. Creating a new PR

2020-03-17 09:33 UTC, boczkowska commented
Closing in favour of https://github.com/eclipse/che-docs/pull/1141

2020-03-17 09:33 UTC, closed without merging