Fixing headings in the Overview section
eclipse-che/che-docs pull request #1167
Opened 2020-03-25 15:47 UTC by MichalMaler

Signed-off-by: Michal Maléř <mmaler@redhat.com>

* Checking Overview IDs uniqueness
* Adding missing _{context} attribute to assembly headings
* Adding context information for included files
* Adding :page-liquid: where needed
* Deleting unnecessary content (empty templates without its place in the doc plan https://github.com/eclipse/che/issues/14415)
* Reworking `Installing Che using storage classes` and placing it in *IG/ Advanced configuration options - Checked by Oleksandr Andriienko and Serhii Leshchenko *

2020-03-25 16:43 UTC, rkratky requested changes
Nice job, @MichalMaler -- good to have consistency. A few comments added.

2020-03-25 16:43 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
> +:context: proc_installing-{prod-id-short}-using-storage-classes
The context should not include "proc_".
```suggestion
:context: installing-{prod-id-short}-using-storage-classes
```

2020-03-25 16:43 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
> +:context: proc_installing-{prod-id-short}-using-storage-classes
Just realized... this a module included from an assembly. It shouldn't set its own context at all.
```suggestion
```

2020-03-25 16:43 UTC, rkratky commented on src/main/pages/che-7/overview/assembly_accessing-che-from-openshift-developer-perspective.adoc
> +
Parent context should be set.
```suggestion
 :parent-context-of-accessing-che-from-openshift-developer-perspective: {context}
 
```

2020-03-25 16:43 UTC, rkratky commented on src/main/pages/che-7/overview/assembly_accessing-che-from-openshift-developer-perspective.adoc
> +
Also, reset the context at the end of the assembly with:
```
:context: {parent-context-of-accessing-che-from-openshift-developer-perspective}
```
(I can't add it as a suggestion.)

2020-03-25 17:05 UTC, MichalMaler commented
Hi, @rkratky Thx for the quick and kind feedback! Suggestions are on the way

2020-03-26 10:53 UTC, rkratky approved these changes

2020-03-26 10:54 UTC, merged