I1724 ibm style guide
eclipse-che/che-docs pull request #1221
Opened 2020-04-15 11:47 UTC by MichalMaler

Signed-off-by: Michal Maléř <mmaler@redhat.com>

Replacing words and rewording the content if needed.

2020-04-15 15:15 UTC, rkratky requested changes

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
> +|`IMAGES` |List of images to be cached, in the format `<name>=<image>;...` |Contains a default list of images. Configuration in the pre-deploying state recommended
This changes meaning. Why **pre**-deploying?

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
> +the user's {prod-short} authentication token can be retrieved from the user's OpenShift one.
```suggestion
the user's {prod-short} authentication token can be retrieved from the user's OpenShift token.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
> +WARNING: Before using this token exchange feature, it is required for an end user to be interactively logged in {prod-short} Dashboard using the OpenShift login page at least once. This step is neede
```suggestion
WARNING: Before using this token exchange feature, it is required for an end user to be interactively logged in at least once to the {prod-short} Dashboard using the OpenShift login page. This step is needed to link the OpenShift and {identity-provider} user accounts properly and set the required user profile information.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/administration-guide/proc_detecting-memory-problems.adoc
> +This can happen during plug-in initialization when the container does not have enough RAM to execute the entrypoint of the image. The user can detect this in the logs of the plug-in container. In thi
```suggestion
This can happen during plug-in initialization when the container does not have enough RAM to execute the entrypoint of the image. The user can detect this in the logs of the plug-in container. In this case, the logs contain `OOMKilled`, which implies that the processes in the container requested more memory than is available in the container.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/administration-guide/proc_detecting-memory-problems.adoc
> +To detect this problem, check the logs of the primary process, running in the container. For example, to check the log file of Eclipse JDT Language Server for details, see the relevant plug-in-specif
```suggestion
To detect this problem, check the logs of the primary process running in the container. For example, to check the log file of Eclipse JDT Language Server for details, see the relevant plug-in-specific sections.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
> +<2> The identifier of the command, which invokes when the shortcut is pressed.
```suggestion
<2> The identifier of the command invoked when the shortcut is pressed.
```
(A transitive verb, which requires an object.)

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
> +| `id` | Language ID; has to correspond to the `id` in the configuration JSON file
This changes meaning. Rather use:
```suggestion
| `id` | Language ID; it has to be the same as the `id` in the configuration JSON file
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
>  * multi-host
```suggestion
* `multi-host`
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
>  * single-host
```suggestion
* `single-host`
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
>  * default-host
```suggestion
* `default-host`
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
> +In case of the multi-host strategy, you must set the che.infra.kubernetes.ingress.domain (or the `CHE_INFRA_KUBERNETES_INGRESS_DOMAIN` environment variable) configuration property to the domain name
```suggestion
For the multi-host strategy, set the che.infra.kubernetes.ingress.domain (or the `CHE_INFRA_KUBERNETES_INGRESS_DOMAIN` environment variable) configuration property to the domain name that will host workspace component subdomains.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
> +.Example:
```suggestion
.Example
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
> +The `FROM` directive must correspond to `FROM eclipse/che-theia-endpoint-runtime:next`. This is required since the base image contains tools for running the remote VS Code extension and communicating
This changes meaning.
```suggestion
Base the `FROM` directive on `FROM eclipse/che-theia-endpoint-runtime:next`. This is required because the base image contains tools for running the remote VS Code extension and for communicating between the sidecar and the Che-Theia editor. This way, the VS Code extension operates as if it was not remote.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
> +.{prod-short} {prod-ver} stacks and their corresponding {prod-short} {prod-prev-ver} devfiles
Nice.

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
> +* GitHub OAuth is configured, see link:{site-baseurl}che-7/configuring-github-oauth/[Configuring GitHub OAuth].
```suggestion
* GitHub OAuth is configured. See link:{site-baseurl}che-7/configuring-github-oauth/[Configuring GitHub OAuth].
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
> +A single devfile can specify multiple projects. For each project, specify the type of the source repository, its location, and, optionally, the directory the project will be cloned to.
```suggestion
A single devfile can specify multiple projects. For each project, specify the type of the source repository, its location, and, optionally, the directory the project is cloned to.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
> +<18> A list of VS Code extensions that is run in this sidecar container.
```suggestion
<18> A list of VS Code extensions run in this sidecar container.
```
(It's not the list that's run.)

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
>  `category`: Available \: `Language`, `Other`
```suggestion
`category`: Available\: `Language`, `Other`
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +The trailing slash indicates that only directories with the given name (including their content) will be created.
```suggestion
The trailing slash indicates that only directories with the given name (including their content) are created.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +* `unsecuredPaths`: A comma-separated list of the unsecured endpoint paths, staying as unsecured even if the `secure` attribute is set to `true`.
Confusing.
```suggestion
* `unsecuredPaths`: A comma-separated list of endpoint paths that are to stay unsecured even if the `secure` attribute is set to `true`.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +Each {prod-short}-specific command has an *action* attribute that is a command to execute and a *component* attribute that specifies the container for the command execution. The commands are run usin
```suggestion
Each {prod-short}-specific command features:

 * An `action` attribute that is a command to execute.
 * A `component` attribute that specifies the container in which to execute the command.
 
 The commands are run using the default shell in the container.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +* `on` -- enables a notification that ask the user about the URL opening preferences
```suggestion
* `on` -- enables a notification for asking the user about the URL opening preferences
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +When an editor is not specified in a devfile, a default is provided. When no editor is needed, the `editorFree` attribute is applied. The default value is `false`, and it means that the devfile needs
Change in meaning.
```suggestion
When an editor is not specified in a devfile, a default is provided. When no editor is needed, use the `editorFree` attribute. The default value of `false` means that the devfile requests the provisioning of the default editor.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +By default, volumes and PVCs specified in a devfile are bound to a host folder to persist data even after a container restart. Sometimes, it may be necessary to disable data persistence, such as when
```suggestion
By default, volumes and PVCs specified in a devfile are bound to a host folder to persist data even after a container restart. To disable data persistence to make the workspace faster, such as when the volume back end is slow, modify the `persistVolumes` attribute in the devfile. The default value is `true`. Set to `false` to use `emptyDir` for configured volumes and PVC.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
> +COBOL Language Support standardizes the communication between language tools and your code editor using the Language Server Protocol (LSP)
```suggestion
COBOL Language Support standardizes the communication between language tools and the code editor using the Language Server Protocol (LSP).
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
> +WARNING: There are legacy variables `CHE_INFRA_KUBERNETES_NAMESPACE` and `CHE_INFRA_OPENSHIFT_PROJECT`. Keep these variables unset for a new installations. Changing these variables during an update c
Nice.

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
> +`securityContextFsGroup,omitempty`: `1724`: FSGroup the {prod-short} Pod and Workspace Pods containers will run in.
```suggestion
`securityContextFsGroup,omitempty`: `1724`: FSGroup the {prod-short} Pod and Workspace Pods containers run in.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
> +`securityContextRunAsUser`: `1724`: ID of the user the {prod-short} Pod and Workspace Pods containers will run as.
```suggestion
`securityContextRunAsUser`: `1724`: ID of the user the {prod-short} Pod and Workspace Pods containers run as.
```

2020-04-15 15:15 UTC, rkratky commented on src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
> +When installing {prod} in the `default` namespace, the proper security contexts and file permissions are not set appropriately, causing the installation to fail. It is recommended for users to avoid
```suggestion
When installing {prod} in the `default` namespace, the proper security contexts and file permissions are not set appropriately, causing the installation to fail. Recommendation: do not install {prod-short} in the `default` namespace. Instead, create a new namespace, for example, `{project-context}`, to contain the {prod-short} installation.
```

2020-04-15 16:51 UTC, MichalMaler commented on src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
> +|`IMAGES` |List of images to be cached, in the format `<name>=<image>;...` |Contains a default list of images. Configuration in the pre-deploying state recommended
Will change this to -> `Before deploying, fill this with the images that fit the current requirements.`

2020-04-16 09:37 UTC, rkratky approved these changes

2020-04-16 09:37 UTC, merged