Change docs according self-signed certificate flag automation
eclipse-che/che-docs pull request #1331
Opened 2020-06-24 12:17 UTC by mmorhun

Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

### What does this PR do?
Updates docs according to automation of `--self-signed-certificate` flag.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16764

### Specify the version of the product this PR applies to. 
Eclipse Che 7.15.0

2020-06-24 13:58 UTC, AndrienkoAleksandr commented on src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
> +WARNING: Self-signed certificates is usually used in development and evaluation enviromnents. If you want to use them in production you should understand the consequences.
enviromnents -> environments

2020-06-28 17:20 UTC, rkratky requested changes
Submitted my review and suggested changes in #1340.

2020-06-28 17:20 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
> +WARNING: Self-signed certificates is usually used in development and evaluation enviromnents. If you want to use them in production you should understand the consequences.
```suggestion
WARNING: Self-signed certificates are usually used in development and evaluation environments. Use in production environments is not recommended.
```

2020-06-30 16:00 UTC, rkratky approved these changes

2020-06-30 16:07 UTC, rkratky commented
@mmorhun, thanks for the updates. As mentioned in #1340, I'm merging this in your absence, but I'll be happy to revisit it if needed.

2020-06-30 16:07 UTC, merged