Substitutions: script output and human revision
eclipse-che/che-docs pull request #1363
Opened 2020-07-03 12:43 UTC by themr0c

Substitutions: script output and human revision

2020-07-03 13:05 UTC, rkratky requested changes

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/extensions/assembly_telemetry.adoc
> +Telemetry is the transparent and ethical collection of the usage data. By default, telemetry is not available in the {prod}, but there is an abstract API that allows enabling telemetry via the plug-i
```suggestion
Telemetry is the transparent and ethical collection of the usage data. By default, telemetry is not available in the {prod}, but there is an abstract API that allows enabling telemetry via the plug-in mechanism. This approach is used in the link:{site-baseurl}che-7/hosted-che/[Hosted Che] service where telemetry is enabled for every workspace.
```
It actually is "Hosted Che", so no sub here.

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/extensions/assembly_telemetry.adoc
> +Create a `meta.yaml` definition representing a Che Plugin that runs your custom back-end in a workspace Pod. For more information on `meta.yaml`, see link:{site-baseurl}che-7/what-is-a-{prod-id-short
```suggestion
Create a `meta.yaml` definition representing a {prod-short} plug-in that runs your custom back-end in a workspace Pod. For more information on `meta.yaml`, see link:{site-baseurl}che-7/what-is-a-che-theia-plug-in/[What is a Che-Theia plug-in].
```
This was correct (discussed on Slack).

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/extensions/assembly_telemetry.adoc
> +Update the `CheCluster` custom resource, and add the `CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS` environment variable to `spec.server.customCheProperties`. The value of the environment variable s
```suggestion
Update the `CheCluster` custom resource, and add the `CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS` environment variable to `spec.server.customCheProperties`. The value of the environment variable should be the URL of the location of the `meta.yaml` file on your web server.  This can be accomplished by running `oc edit checluster -n che` and typing in the change at the terminal, or by editing the CR in the OpenShift console (*Installed Operators -> {prod} -> {prod} Cluster -> {prod-checluster} -> YAML*).
```

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
> +* xref:upgrading-from-{prod-id-short}-{prod-prev-ver-major}-on-openshift-4-using-the-web-console_{context}[]
This will evaluate as "6.x" --> make sure the xref will still work.

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
> +include::proc_upgrading-from-{prod-id-short}-{prod-prev-ver-major}-on-openshift-4-using-the-web-console.adoc[leveloffset=+1]
This will evaluate as "6.x" --> make sure the file name is really called that.

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
> +* For Helm Chart deployments, set the following environment variable in the {prod-short} config map:
```suggestion
* For Helm Chart deployments, set the following environment variable in the {prod-short} ConfigMap:
```

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
> +[id="upgrading-from-{prod-id-short}-{prod-prev-ver-major}-on-openshift-4-using-the-web-console_{context}"]
This will evaluate as "6.x" --> make sure the (old) ID is either not referenced in a link/xref, or the link/xxref is updated, too.

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
> +[id="hosted-{prod-id-short}-faq-and-troubleshooting_{context}"]
```suggestion
[id="hosted-che-faq-and-troubleshooting_{context}"]
```

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
> +**Q**: Where can I see the up-to-date status of the {prod} hosted by Red Hat?
```suggestion
**Q**: Where can I see the up-to-date status of Eclipse Che hosted by Red Hat?
```

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
> +=== Cannot log into the Hosted {prod-short} - Authorization token is missed
```suggestion
=== Cannot log into the Hosted Che - Authorization token is missed
```

2020-07-03 13:05 UTC, rkratky commented on src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
> +Also, note that telemetry is enabled in Hosted {prod-short} so Woopra / Segment tracking scripts must be explicitly allowed in case being blocked by a browser extension:
```suggestion
Also, note that telemetry is enabled in Hosted Che, so Woopra or Segment tracking scripts must be explicitly allowed if blocked by a browser extension:
```

2020-07-06 07:30 UTC, themr0c commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
> +[id="upgrading-from-{prod-id-short}-{prod-prev-ver-major}-on-openshift-4-using-the-web-console_{context}"]
so as said: switching to prod-prev-ver-major: 6

2020-07-06 09:12 UTC, rkratky approved these changes

2020-07-06 09:14 UTC, merged