Remove unused CI files. We don't use ant anymore.
eclipse-che/che-docs pull request #1525
Opened 2020-09-03 12:03 UTC by themr0c

Remove unused CI files. We don't use ant anymore. fixes https://github.com/eclipse/che/issues/17778

2020-09-03 12:12 UTC, mkuznyetsov requested changes, later dismissed
please do not remove "make-release.sh", as it is currently used for generating tags during releases

2020-09-03 13:35 UTC, themr0c commented
I restored the file, thanks @mkuznyetsov !

2020-09-03 13:41 UTC, rkratky approved these changes

2020-09-04 08:29 UTC, themr0c commented
There is a dependency on pom.xml in ./tools/environment_docs_gen.sh. I have to fix it before merge.
```
Trying to read current product version from pom.xml...
grep: /home/jenkins/agent/workspace/che-docs-pipeline_PR-1525/che-docs/pom.xml: No such file or directory
```

2020-09-04 09:36 UTC, merged