Provision GitHub OAuth using secret
eclipse-che/che-docs pull request #1773
Opened 2021-01-04 09:51 UTC by tolusha

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Describe how to provision GitHub OAuth with secrets

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18238

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [x] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

![screenshot-0 0 0 0_4000-2021 01 04-11_49_33](https://user-images.githubusercontent.com/1640675/103522472-18e0cc80-4e83-11eb-8592-6c381b1b04b4.png)

2021-01-04 12:51 UTC, boczkowska approved these changes

2021-01-05 08:49 UTC, tolusha commented
@boczkowska 
Could you help me to fix linkchecker issue ?

2021-01-05 09:49 UTC, themr0c commented
@tolusha I fixed some linkchecker issues yesterday, maybe a rebase will help?

2021-01-05 09:52 UTC, boczkowska commented
@tolusha @themr0c after the re-run of the job, no more failures :D the websites it tried to reach seemed to be unavailable at the time

2021-01-05 09:55 UTC, themr0c commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +. Set up the link:https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app[GitHub OAuth client] with `https://{prod-deployment}-{prod-namespace}.<DOMAIN>/` and `https://keycloak-{p
```suggestion
. Set up the link:https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app[GitHub OAuth client] with `https://{prod-deployment}-{prod-namespace}.<DOMAIN>/` and `https://keycloak-{prod-namespace}.<DOMAIN>/auth/realms/{prod-deployment}/broker/github/endpoint` as Homepage and Authorization callback URLs correspondingly, where `<DOMAIN>` is {orch-name} cluster domain.
```

2021-01-06 07:00 UTC, tolusha commented
Can we merge this ?

2021-01-06 08:24 UTC, l0rd commented
> Can we merge this ?

Let me review it first

2021-01-06 20:47 UTC, l0rd requested changes
Comment not really related to this PR but that need to be fixed (in this or in another PR):

- this procedure should not be in the end-user guide, it should be in the admin guide.
- "OAuth for GitHub allows for automatic SSH key upload to GitHub.". That's just part of it. The main reason is to support VS Code extensions that require GitHub authentication (like the GitHub Pull Request).

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +* A running instance of {prod}. To install an instance of {prod}, see {link-installing-an-instance}.
We do not really need a running instance of Che. We need to know Che and Keyckloak URL though.

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +. Set up the link:https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app[GitHub OAuth client] with `https://{prod-deployment}-{prod-namespace}.<DOMAIN>/` and `https://keycloak-{p
Instead of "Set up the GitHub OAuth client" it would be better to say "Create a new OAuth App in GitHub".

And the URLs you are providing are the default ones (`{prod-deployment}-{prod-namespace}`) but the user may use a different deployment name and namespace.

 ```suggestion
. Create a link:https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app[OAuth application in GitHub] using {prod-short} URL as the value for the application `Homepage URL` and {identity-provider} GitHub endpoint URL as the value for Authorization callback URL. The default values are `https://{prod-deployment}-{prod-namespace}.<DOMAIN>/` and `https://keycloak-{prod-namespace}.<DOMAIN>/auth/realms/{prod-deployment}/broker/github/endpoint` respectively, where `<DOMAIN>` is {orch-name} cluster domain.
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +  namespace: {prod-namespace}
```suggestion
  namespace: <...> <1>
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +  id: <...> <1>
```suggestion
  id: <...> <2>
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +  secret: <...> <2>
```suggestion
  secret: <...> <3>
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +<1> base64 encoded GitHub OAuth Client ID
```suggestion
<1> {prod-short} namespace. The default is {prod-namespace}
<2> base64 encoded GitHub OAuth Client ID
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +<2> base64 encoded GitHub OAuth Client Secret
```suggestion
<3> base64 encoded GitHub OAuth Client Secret
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +. Wait until rollout of {identity-provider} component finishes.
```suggestion
. If {prod-short} was already installed wait until rollout of {identity-provider} component finishes.
```

2021-01-06 20:47 UTC, l0rd commented on modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
> +* For {prod-short} deployed in multi-user mode:
The configuration of the GitHub OAuth application is common to both multi-user and single-user mode. This line should be moved below.

2021-01-08 08:49 UTC, tolusha commented
@themr0c 
Could you find a better place in admin guide to move the doc to ?

2021-01-11 10:49 UTC, tolusha commented
@l0rd 
Moved to admin guide

2021-01-13 13:28 UTC, l0rd approved these changes
LGTM. Thank you @tolusha

2021-01-13 15:18 UTC, merged