Generate checluster references tables
eclipse-che/che-docs pull request #1803
Opened 2021-01-21 12:28 UTC by tolusha

Signed-off-by: Anatolii Bazko <abazko@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Add scripts to sync doc and checluster crd

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/RHDEVDOCS-2216

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

2021-01-21 12:38 UTC, MichalMaler approved these changes

2021-01-21 13:15 UTC, MichalMaler commented
LGTM. We are waiting for @l0rd approval now.

2021-01-22 07:48 UTC, tolusha commented
gen script requires `yq` installed since it will be run on Jenkins

2021-01-22 08:56 UTC, MichalMaler commented
> gen script requires `yq` installed since it will be run on Jenkins

We can add:

.Prerequisites
* The `yq` tool is available. See link:https://pypi.org/project/yq/[yq homepage].

2021-01-22 10:45 UTC, themr0c commented
The che-docs container has `yq` inside.

2021-01-22 10:47 UTC, themr0c commented
Can you confirm it runs on che.openshift.io?

2021-01-22 10:54 UTC, tolusha commented
I've just checked:
1. Created a workspace from the devfile [1]
2. Run command in `che-docs` containers.
yes, it exists there.

[1] https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml

2021-01-22 10:55 UTC, themr0c commented
@MichalMaler the requirement is to build the docs, not to the user-facing docs.

2021-01-22 10:58 UTC, themr0c requested changes
Can you fix the shellcheck errors:

shellcheck tools/checluster_docs_gen.sh 

In tools/checluster_docs_gen.sh line 17:
TABLE_HEADER="$NEWLINE[cols=\"2,5\", options="header"]$NEWLINE:=== $NEWLINE Property: Description $NEWLINE"
              ^-- SC1087: Use braces when expanding arrays, e.g. ${array[idx]} (or ${var}[.. to quiet).
                                              ^----^ SC2140: Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?


In tools/checluster_docs_gen.sh line 19:
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." ; pwd -P )
               ^-- SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.

Did you mean: 
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit ; pwd -P )


In tools/checluster_docs_gen.sh line 27:
  if [ $? -ne 0 ]; then
       ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.


In tools/checluster_docs_gen.sh line 41:
  if [ $? -ne 0 ]; then
       ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.


In tools/checluster_docs_gen.sh line 59:
  if [ $? -ne 0 ]; then
       ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.


In tools/checluster_docs_gen.sh line 88:
    local section=$(echo "$RAW_CONTENT" | yq -M '.spec.validation.openAPIV3Schema.properties.status')
          ^-----^ SC2155: Declare and assign separately to avoid masking return values.


In tools/checluster_docs_gen.sh line 90:
    local section=$(echo "$RAW_CONTENT" | yq -M '.spec.validation.openAPIV3Schema.properties.spec.properties.'$sectionName)
          ^-----^ SC2155: Declare and assign separately to avoid masking return values.
                                                                                                              ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    local section=$(echo "$RAW_CONTENT" | yq -M '.spec.validation.openAPIV3Schema.properties.spec.properties.'"$sectionName")


In tools/checluster_docs_gen.sh line 94:
    $(echo "$section" | yq -M '.properties | keys[]' )
    ^-- SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).


In tools/checluster_docs_gen.sh line 103:
    description=$(echo "$section" | yq -M '.properties.'$prop'.description')
                                                        ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    description=$(echo "$section" | yq -M '.properties.'"$prop"'.description')

For more information:
  https://www.shellcheck.net/wiki/SC1087 -- Use braces when expanding arrays,...
  https://www.shellcheck.net/wiki/SC2140 -- Word is of the form "A"B"C" (B in...
  https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...

2021-01-22 11:33 UTC, tolusha commented
@themr0c 
Sorry, to be honest I don't think that they are relevant. Where did they come from ?

2021-01-25 17:47 UTC, l0rd commented
> @themr0c
> Sorry, to be honest I don't think that they are relevant. Where did they come from ?

@tolusha [shellcheck](https://github.com/koalaman/shellcheck) is the most widespread linter for bash scripts (22K stars) and it's [common](https://github.com/eclipse/che/pull/17865) [to run](https://github.com/eclipse/che/pull/13542#discussion_r299337657) [our scripts](https://github.com/eclipse/che/pull/12455/commits/b818fccea3496f85579ad1affaf880674bb718f1) against it.

2021-01-26 07:45 UTC, tolusha commented
@themr0c 
Fixed

2021-01-26 08:54 UTC, MichalMaler commented
@themr0c Fabrice, I think we are good to go here :) 
Good job @tolusha  and thank you, @themr0c for setting up the linter.

2021-01-26 09:00 UTC, tolusha commented
```bash
$ shellcheck checluster_docs_gen.sh 
$ 
```

no issues with spellchecker anymore ...

2021-01-26 09:38 UTC, themr0c commented
So now, what can we do for the vale errors?

2021-01-26 09:41 UTC, MichalMaler commented
let me take a look

2021-01-26 09:45 UTC, themr0c commented
To fix vale errors:

For the static file, `ref_checluster-custom-resource-fields-reference.adoc`, this is straightforward: fix all vale errors in place.

For the generated file:
* Long term: fix the upstream of the file.
* Short term: substitutions, as we do with `environment_docs_gen.sh`

2021-01-26 10:01 UTC, themr0c commented on tools/checluster_docs_gen.sh
> +  CURRENT_VERSION=$(grep 'prod-ver:' "$PARENT_PATH/antora-playbook.yml" | cut -d: -f2 | sed  's/ //g').x
As we have `yq` as a dependency, you can use it here too.

2021-01-26 10:06 UTC, tolusha commented
Too much of vale errors, that's not possible to fix at script using substitution. 
I suggest the following:
1. Fix build error and merge.
2. Doc team reviews CRD file to fix descriptions there.
3. Regenerate the doc with a new CRD

2021-01-26 10:22 UTC, themr0c commented on tools/checluster_docs_gen.sh
> +  PRODUCT=$(grep 'prod-id-short:' "$PARENT_PATH/antora-playbook.yml" | cut -d: -f2 | sed  's/ //g')
use `yq` here topo?

2021-01-26 10:52 UTC, themr0c commented on tools/checluster_docs_gen.sh
> +# Copyright (c) 2018 Red Hat, Inc.
```suggestion
# Copyright (c) 2021 Red Hat, Inc.
```

2021-01-26 13:10 UTC, MichalMaler commented
> To fix vale errors:
> 
> For the static file, `ref_checluster-custom-resource-fields-reference.adoc`, this is straightforward: fix all vale errors in place.
> 
> For the generated file:
> 
> * Long term: fix the upstream of the file.
> * Short term: substitutions, as we do with `environment_docs_gen.sh`

Here is my Vale fix in the file, but I am concern that this was useless work since I was working on this instead of monitoring your conversation.

@tolusha Please, can you use it to fix the Origin?

2021-01-29 09:46 UTC, themr0c commented
Some hints to move forward in testing and validating this PR:

To run the script in `che-docs`:

* Backport the file in che-operator to the `7.25` release. This is the only option to validate properly the PR in che-docs.
* Same thing for the `7.24` release.
* To test and validate beforehand (don't commit in the PR): change the `prod-ver` value to `master` in `antora-playbook.yml`

To run `vale` in `che-operator` repository which has no .vale.ini

* Point vale to the che-docs config file  
```vale --config='some/file/path/.vale.ini'```

2021-01-29 12:58 UTC, tolusha commented
@themr0c 
Thank you. I will handle that.

But there is an open question: Jenkins build failed.
I think docker image contains incorrect yq package.
It should be https://github.com/kislyuk/yq instead of  http://mikefarah.github.io/yq/

2021-01-29 15:16 UTC, themr0c commented
So 
```
pip3 install yq
```
Instead of 

```
apk add yq
```?

2021-01-29 15:29 UTC, themr0c commented
@tolusha Waiting for validation of https://github.com/eclipse/che-docs/pull/1822 before pushing the new che-docs container to quay.

2021-02-04 09:34 UTC, themr0c commented
@tolusha the correct version of `yq` is now available in the che-docs container.

2021-02-04 10:19 UTC, themr0c approved these changes

2021-02-04 10:24 UTC, themr0c commented
As we still have lots of language errors, if we merge now, we'll need a follow-up task to:
- fix the language in the source of these generated docs,
- then adapt the script to execute substitutions for what can't be changed upstream (prod-short attribute instead of Che).

2021-02-04 10:47 UTC, tolusha commented
@themr0c 
We agreed with @MichalMaler to review the source one more time.

2021-02-04 10:57 UTC, MichalMaler commented
I will do it when I take care of RNaKI. Hope I will start with this task today.

2021-02-10 14:12 UTC, tolusha commented
I've just updated PR based on the latest changes from master branch of che-operator to see if we have any vale errors.

2021-02-12 11:47 UTC, tolusha commented
I've update checluster doc based on master che-operator branch. So, we don't have value errors anymore.
But jenkins still fails.

2021-02-12 12:06 UTC, tolusha commented
NB: If PR is merged then checluster references tables will be regenerated based on 7.25 version of che-operator (from antora-playbook.yaml) which doesn't contain all vale fixes.

2021-02-12 12:11 UTC, MichalMaler approved these changes

2021-02-15 10:44 UTC, merged