Fix dead links to Zowe CLI Plug-ins
eclipse-che/che-docs pull request #1831
Opened 2021-02-02 15:34 UTC by zeibura

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Fixes links to Zowe CLI Plug-ins

### What issues does this PR fix or reference?
#18788

### Specify the version of the product this PR applies to.

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [ ] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

2021-02-02 15:49 UTC, zeibura commented
I'm not sure why the "link checker" bot is failing, it seems to have a problem with a link "https://websocketstest.com/" which is nowhere in this file.

2021-02-02 16:09 UTC, themr0c commented
Yes, this error started today, see  https://github.com/eclipse/che/issues/18947

2021-02-02 16:11 UTC, themr0c commented
@zeibura If you want that the link appears again, you need to uncomment the lines.

2021-02-02 16:26 UTC, zeibura commented
Which link? Uncomment which lines?

2021-02-03 08:36 UTC, benoitf approved these changes

2021-02-03 08:37 UTC, benoitf commented
it will require https://github.com/eclipse/che-docs/pull/1832 to be merged and rebased to have linkchecker PR check passing

2021-02-03 08:42 UTC, themr0c requested changes

2021-02-03 08:42 UTC, themr0c commented on modules/extensions/partials/assembly_eclipse-che4z.adoc
> +// * https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html[IBM CICS plug-in for Zowe CLI]
The links are commented out and don't appear in the docs. If they need to appear again, uncomment them, like this:

```suggestion
 * https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-endevor-scm-plug-in-for-zowe-cli.html[CA Endevor SCM plug-in for Zowe CLI]
 * https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-file-master-plus-plug-in-for-zowe-cli.html[CA File Master Plus plug-in for Zowe CLI]
 * https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-db2-database.html[IBM Db2 plug-in for Zowe CLI]
 * https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html[IBM CICS plug-in for Zowe CLI]
```

2021-02-04 09:21 UTC, themr0c approved these changes
Let's move forward

2021-02-11 09:00 UTC, themr0c commented
One last rebase and we can merge this. Thank you, @zeibura.

2021-02-11 09:02 UTC, merged