chore: Add PostgreSQL migration guides
eclipse-che/che-docs pull request #2163
Opened 2021-11-12 13:43 UTC by tolusha

Signed-off-by: Anatolii Bazko <abazko@redhat.com>

## What does this pull request change?
* Add PostgreSQL migration guides

## What issues does this pull request fix or reference?
* https://github.com/eclipse/che/issues/20757
* https://github.com/eclipse/che/issues/20712

## Specify the version of the product this pull request applies to

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

2021-11-18 07:49 UTC, tolusha commented
![migration-external-db](https://user-images.githubusercontent.com/1640675/142373906-47c05e8d-938c-4de6-bc66-e4b67c60e9ab.png)

2022-01-10 12:59 UTC, themr0c commented on modules/administration-guide/partials/snip_finding-che-user-name.adoc
> +CHE_USER_NAME=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser';
```suggestion
[subs="+quotes,+attributes"]
----
POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresSecret')
CHE_USER_NAME=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser'; else {orch-cli} get secret $POSTGRES_SECRET -n {prod-namespace} -o json | jq -r '.data.user' | base64 -d; fi)
----
```

2022-01-25 15:09 UTC, themr0c commented
@tolusha I see merge conflicts, can you resolve them or do you need assistance?

2022-04-11 12:21 UTC, themr0c commented
I apologize for the erroneous closing. My mistake.

2022-04-17 20:26 UTC, themr0c commented
Is the content of this pull request still relevant?

2022-04-18 09:08 UTC, tolusha commented
It is nice to have but I don't have spare time to resolve conflicts.

2022-04-25 13:49 UTC, l0rd commented
@tolusha there was some confusion about this documentation today. Can you please confirm that:
- this is not related to the [instructions to uprade to devworkspace-based Che](https://github.com/eclipse/che/issues/20614)
- this is still relevant even after the switch to the DevWorkspace

2022-04-26 07:27 UTC, tolusha commented
@l0rd 
I can confirm:

1. This is not related to the https://github.com/eclipse/che/issues/20614
2. This is still relevant even after the switch to the DevWorkspace

2022-10-17 08:33 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-down-operator.adoc
> +. Scale down Operator deployment:
```suggestion
. Scale down the Operator deployment:
```

2022-10-17 08:35 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-operator.adoc
> +. Scale up Operator deployment:
```suggestion
. Scale up the Operator deployment:
```

2022-10-17 08:35 UTC, max-cx commented on modules/administration-guide/partials/snip_verification-che-working.adoc
> +. Open Dashboard:
```suggestion
. Open the dashboard:
```

2022-10-17 08:36 UTC, max-cx commented on modules/administration-guide/partials/snip_verification-che-working.adoc
> +. Log in the {prod}.
```suggestion
. Log in to the {prod}.
```

2022-10-17 08:37 UTC, max-cx commented on modules/administration-guide/partials/snip_verification-che-working.adoc
> +{prod-cli} dashboard:open -n {prod-namespace}
```suggestion
$ {prod-cli} dashboard:open -n {prod-namespace}
```

2022-10-17 08:38 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-postgresql.adoc
> +{orch-cli} scale deployment postgres --replicas=1 -n {prod-namespace}
```suggestion
$ {orch-cli} scale deployment postgres --replicas=1 -n {prod-namespace}
```

2022-10-17 08:38 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-postgresql.adoc
> +{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=postgres -n {prod-namespace} --timeout=120s
```suggestion
$ {orch-cli} scale deployment postgres --replicas=1 -n {prod-namespace}
$ {orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=postgres -n {prod-namespace} --timeout=120s
```

2022-10-17 08:38 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-operator.adoc
> +{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component={prod-operator} -n {prod-namespace} --timeout=120s
```suggestion
$ {orch-cli} scale deployment {prod-operator} --replicas=1 -n {prod-namespace}
$ {orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component={prod-operator} -n {prod-namespace} --timeout=120s
```

2022-10-17 08:39 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-keycloak.adoc
> +{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=keycloak -n {prod-namespace} --timeout=120s
```suggestion
$ {orch-cli} scale deployment keycloak --replicas=1 -n {prod-namespace}
$ {orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=keycloak -n {prod-namespace} --timeout=120s
```

2022-10-17 08:39 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-up-che.adoc
> +{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component={prod-deployment} -n {prod-namespace} --timeout=120s
```suggestion
$ {orch-cli} scale deployment {prod-deployment} --replicas=1 -n {prod-namespace}

$ {orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component={prod-deployment} -n {prod-namespace} --timeout=120s
```

2022-10-17 08:39 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-down-postgresql.adoc
> +{orch-cli} scale deployment postgres --replicas=0 -n {prod-namespace}
```suggestion
$ {orch-cli} scale deployment postgres --replicas=0 -n {prod-namespace}
```

2022-10-17 08:39 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-down-operator.adoc
> +{orch-cli} scale deployment {prod-operator} --replicas=0 -n {prod-namespace}
```suggestion
$ {orch-cli} scale deployment {prod-operator} --replicas=0 -n {prod-namespace}
```

2022-10-17 08:40 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-down-keycloak.adoc
> +{orch-cli} scale deployment keycloak --replicas=0 -n {prod-namespace}
```suggestion
$ {orch-cli} scale deployment keycloak --replicas=0 -n {prod-namespace}
```

2022-10-17 08:40 UTC, max-cx commented on modules/administration-guide/partials/snip_scaling-down-che.adoc
> +{orch-cli} scale deployment {prod-deployment} --replicas=0 -n {prod-namespace}
```suggestion
$ {orch-cli} scale deployment {prod-deployment} --replicas=0 -n {prod-namespace}
```

2022-10-17 08:40 UTC, max-cx commented on modules/administration-guide/partials/snip_restoring-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql keycloak < /tmp/keycloak.sql"
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql keycloak < /tmp/keycloak.sql"
```

2022-10-17 08:40 UTC, max-cx commented on modules/administration-guide/partials/snip_restoring-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql $CHE_POSTGRES_DB < /tmp/che.sql"
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql $CHE_POSTGRES_DB < /tmp/che.sql"
```

2022-10-17 08:41 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-postgresql-pod.adoc
> +POSTGRES_POD=$({orch-cli} get pods -n {prod-namespace} | grep postgres | awk '{print $1}')
```suggestion
$ POSTGRES_POD=$({orch-cli} get pods -n {prod-namespace} | grep postgres | awk '{print $1}')
```

2022-10-17 08:41 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-che-user-name.adoc
> +POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresSecret')
```suggestion
$ POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresSecret')
```

2022-10-17 08:41 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-che-user-name.adoc
> +CHE_USER_NAME=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser';
```suggestion
$ CHE_USER_NAME=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser'; else {orch-cli} get secret $POSTGRES_SECRET -n {prod-namespace} -o json | jq -r '.data.user' | base64 -d; fi)
```

2022-10-17 08:42 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-che-user-name.adoc
> +CHE_USER_NAME=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser';
I'm not confident about this suggestion. Is this line a continuation of the previous command?

2022-10-17 08:42 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-che-user-name.adoc
> +echo $CHE_USER_NAME
```suggestion
$ echo $CHE_USER_NAME
```

2022-10-17 08:42 UTC, max-cx commented on modules/administration-guide/partials/snip_finding-che-database-name.adoc
> +CHE_POSTGRES_DB=$({orch-cli} get cm/che -n {prod-namespace} -o json  | jq -r '.data.CHE_JDBC_URL' | awk -F '/' '{print $NF}')
```suggestion
$ CHE_POSTGRES_DB=$({orch-cli} get cm/che -n {prod-namespace} -o json  | jq -r '.data.CHE_JDBC_URL' | awk -F '/' '{print $NF}')
```

2022-10-17 08:42 UTC, max-cx commented on modules/administration-guide/partials/snip_deleting-postgresql-pvc.adoc
> +{orch-cli} delete pvc postgres-data -n {prod-namespace}
```suggestion
$ {orch-cli} delete pvc postgres-data -n {prod-namespace}
```

2022-10-17 08:43 UTC, max-cx commented on modules/administration-guide/partials/proc_updating-postgresql-version.adoc
> +{orch-cli} patch checluster {prod-checluster} -n {prod-namespace} --type=json -p '[{"op": "replace", "path": "/spec/database/postgresVersion", "value": "13.3"}]'
```suggestion
$ {orch-cli} patch checluster {prod-checluster} -n {prod-namespace} --type=json -p '[{"op": "replace", "path": "/spec/database/postgresVersion", "value": "13.3"}]'
```

2022-10-17 08:43 UTC, max-cx commented on modules/administration-guide/partials/proc_restoring-internal-postgresql.adoc
> +{orch-cli} cp keycloak.sql {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql
```suggestion
$ {orch-cli} cp che.sql {prod-namespace}/$POSTGRES_POD:/tmp/che.sql

$ {orch-cli} cp keycloak.sql {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql
```

2022-10-17 08:44 UTC, max-cx commented on modules/administration-guide/partials/proc_restoring-external-postgresql.adoc
> +scp -i <path to public key> che.sql  XXXX@XXX.XXX.XXX.XXX:/tmp
```suggestion
$ scp -i <path to public key> keycloak.sql  XXXX@XXX.XXX.XXX.XXX:/tmp

$ scp -i <path to public key> che.sql  XXXX@XXX.XXX.XXX.XXX:/tmp
```

2022-10-17 08:44 UTC, max-cx commented on modules/administration-guide/partials/proc_restoring-external-postgresql.adoc
> +psql keycloak < /tmp/keycloak.sql
```suggestion
$ psql keycloak < /tmp/keycloak.sql
```

2022-10-17 08:44 UTC, max-cx commented on modules/administration-guide/partials/proc_restoring-external-postgresql.adoc
> +psql <database> < /tmp/che.sql <1>
```suggestion
$ psql <database> < /tmp/che.sql <1>
```

2022-10-17 08:45 UTC, max-cx commented on modules/administration-guide/partials/proc_reinstalling-che.adoc
> +. Remove current {prod} instance by following the instructions xref:installation-guide:uninstalling-che.adoc[].
```suggestion
. Remove the current {prod} instance by following the instructions in xref:installation-guide:uninstalling-che.adoc[].
```

2022-10-17 08:45 UTC, max-cx commented on modules/administration-guide/partials/proc_reinstalling-che.adoc
> +. Deploy a new {prod} instance by following the instructions xref:installation-guide:installing-che.adoc[].
```suggestion
. Deploy a new {prod-short} instance by following the instructions xref:installation-guide:installing-che.adoc[].
```

2022-10-17 08:46 UTC, max-cx commented on modules/administration-guide/partials/proc_provisioning-postgresql.adoc
> +OPERATOR_POD=$({orch-cli} get pods -n {prod-namespace} | grep {prod-operator} | awk '{print $1}')
```suggestion
$ OPERATOR_POD=$({orch-cli} get pods -n {prod-namespace} | grep {prod-operator} | awk '{print $1}')
```

2022-10-17 08:46 UTC, max-cx commented on modules/administration-guide/partials/proc_provisioning-postgresql.adoc
> +IDENTITY_POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.auth.identityProviderPostgresSecret')
```suggestion
$ IDENTITY_POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.auth.identityProviderPostgresSecret')
```

2022-10-17 08:47 UTC, max-cx commented on modules/administration-guide/partials/proc_provisioning-postgresql.adoc
> +IDENTITY_POSTGRES_PASSWORD=$(if [ -z "$IDENTITY_POSTGRES_SECRET" ] || [ $IDENTITY_POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.s
```suggestion

$ IDENTITY_POSTGRES_PASSWORD=$(if [ -z "$IDENTITY_POSTGRES_SECRET" ] || [ $IDENTITY_POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.auth.identityProviderPostgresPassword'; else {orch-cli} get secret $IDENTITY_POSTGRES_SECRET -n {prod-namespace} -o json | jq -r '.data.password' | base64 -d; fi)
```

2022-10-17 08:48 UTC, max-cx commented on modules/administration-guide/partials/proc_provisioning-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"ALTER USER $CHE_USER_NAME WITH SUPERUSER\""
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE USER keycloak WITH PASSWORD '$IDENTITY_POSTGRES_PASSWORD'\""

$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE keycloak\""

$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak\""

$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"ALTER USER $CHE_USER_NAME WITH SUPERUSER\""
```

2022-10-17 08:49 UTC, max-cx commented on modules/administration-guide/partials/proc_configuring-external-PostgreSQL.adoc
> +echo $CHE_USER_NAME
```suggestion

$ echo $CHE_USER_NAME
```

2022-10-17 08:49 UTC, max-cx commented on modules/administration-guide/partials/proc_configuring-external-PostgreSQL.adoc
>  ALTER USER <database-user> WITH SUPERUSER
```suggestion
$ CREATE USER <database-user> WITH PASSWORD '<database-password>'

$ CREATE DATABASE <database>

$ GRANT ALL PRIVILEGES ON DATABASE <database> TO <database-user>

$ ALTER USER <database-user> WITH SUPERUSER
```

2022-10-17 08:49 UTC, max-cx commented on modules/administration-guide/partials/proc_configuring-external-PostgreSQL.adoc
>  GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak
```suggestion
$ CREATE USER keycloak WITH PASSWORD '<identity-database-password>'

$ CREATE DATABASE keycloak

$ GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +. Drop {identity-provider} database:
```suggestion
. Drop the {identity-provider} database:
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "dropdb keycloak"
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "dropdb keycloak"
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +. Create {identity-provider} database:
```suggestion
. Create the {identity-provider} database:
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE keycloak\""
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE keycloak\""
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +. Drop {prod-short} database:
```suggestion
. Drop the {prod-short} database:
```

2022-10-17 08:50 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "dropdb $CHE_POSTGRES_DB"
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "dropdb $CHE_POSTGRES_DB"
```

2022-10-17 08:51 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +. Create {prod-short} database:
```suggestion
. Create the {prod-short} database:
```

2022-10-17 08:51 UTC, max-cx commented on modules/administration-guide/partials/proc_cleaning-up-postgresql.adoc
> +{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE $CHE_POSTGRES_DB\""
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE $CHE_POSTGRES_DB\""
```

2022-10-17 08:54 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> += Backuping PostgreSQL
```suggestion
[id="backing-up-postgresql{context}"]
= Backing up PostgreSQL
```

2022-10-17 08:55 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> += Backuping PostgreSQL
You'll probably need to change the file name too.

2022-10-17 08:55 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> +. Save and push changes back to the Git repositories for all running workspaces of the {prod-short} instance.
```suggestion
. Save and push changes to the Git repositories for all running workspaces of the {prod-short} instance.
```

2022-10-17 08:56 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> +. Backup {prod-short} database:
```suggestion
. Back up the {prod-short} database:
```

2022-10-17 08:56 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> +{orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/che.sql che.sql
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "pg_dump $CHE_POSTGRES_DB > /tmp/che.sql"

$ {orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/che.sql che.sql
```

2022-10-17 08:56 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> +. Backup {identity-provider} database:
```suggestion
. Back up the {identity-provider} database:
```

2022-10-17 08:56 UTC, max-cx commented on modules/administration-guide/partials/proc_backuping-postgresql.adoc
> +{orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql keycloak.sql
```suggestion
$ {orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "pg_dump keycloak > /tmp/keycloak.sql"

$ {orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql keycloak.sql
```

2022-10-17 08:57 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-to-external-database-setup.adoc
> += Migration to external database setup
```suggestion
[id="migration-to-an-external-database-setup_{context}"]
= Migration to an external database setup
```

2022-10-17 08:57 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-to-external-database-setup.adoc
> += Migration to external database setup
You'll probably need to change the file name too.

2022-10-17 08:59 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-to-external-database-setup.adoc
> +Follow the procedures below to migrate from internal to external database setup successfully without any data loss.
```suggestion
You can migrate from the internal database to an external database without losing data.
```

2022-10-17 09:01 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-from-postgresql-9-to-postgresql-13.adoc
> +Follow the procedures below to migrate to a newer version of PostgreSQL successfully without any data loss.
```suggestion
You can migrate to a newer version of PostgreSQL without losing data.
```

2022-10-17 09:07 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-from-postgresql-9-to-postgresql-13.adoc
> +By the 11th of November, 2021, the PostgreSQL version 9.6 came out of support, and {prod-short} team recommends that all users undergo migrating to version 13.
This looks like a release note to me. If we need to tell this information to customers, I propose that we create a release note and link to this procedure from the release note.
Let me know what you think about this possibility.

2022-10-17 09:09 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-from-postgresql-9-to-postgresql-13.adoc
> +:context: migration-from-postgresql-9-to-postgresql-13
```suggestion
:parent-context-of-upgrading-postgresql: {context}

[id="upgrading-postgresql_{context}"]
= Upgrading PostgreSQL 

:context: upgrading-postgresql
```

2022-10-17 09:09 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-from-postgresql-9-to-postgresql-13.adoc
> +:context: {parent-context-of-migration-from-postgresql-9-to-postgresql-13}
```suggestion
:context: {parent-context-of-upgrading-postgresql}
```

2022-10-17 09:10 UTC, max-cx commented on modules/administration-guide/partials/assembly_migration-from-helm-charts-to-operator.adoc
> +Follow the procedures below to migrate from Helm Charts to Operator successfully without any data loss.
```suggestion
You can migrate from Helm Charts to Operator without losing data.
```

2022-10-17 09:10 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +:navtitle: Migration to external database setup
```suggestion
:navtitle: Migration to an external database setup
```

2022-10-17 09:10 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +[id="migration-to-external-database-setup"]
```suggestion
[id="migration-to-an-external-database-setup"]
```

2022-10-17 09:10 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +[id="migration-to-external-database-setup"]
You'll probably need to change the file name too.

2022-10-17 09:11 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +:navtitle: Migration to external database setup
```suggestion
[id="migration-to-an-external-database-setup"]
:navtitle: Migration to an external database setup
```

2022-10-17 09:12 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +:navtitle: Migration to external database setup
You'll probably need to change the file name too.

2022-10-17 09:12 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +include::partial$assembly_migration-to-external-database-setup.adoc[]
I might have suggested renaming that file too.

2022-10-17 09:13 UTC, max-cx commented on modules/administration-guide/pages/migration-to-external-database-setup.adoc
> +include::partial$assembly_migration-to-external-database-setup.adoc[]
```suggestion
include::partial$assembly_migration-to-an-external-database-setup.adoc[]
```

2022-10-17 09:14 UTC, max-cx commented on modules/administration-guide/pages/migration-from-postgresql-9-to-postgresql-13.adoc
>  :navtitle: Migration from PostgreSQL 9 to PostgreSQL 13
```suggestion
[id="upgrading-postgresql"]
:navtitle: Upgrading PostgreSQL
```

2022-10-17 09:14 UTC, max-cx commented on modules/administration-guide/pages/migration-from-postgresql-9-to-postgresql-13.adoc
> +include::partial$assembly_migration-from-postgresql-9-to-postgresql-13.adoc[]
```suggestion
include::partial$assembly_upgrading-postgresql.adoc[]
```

2022-10-17 09:15 UTC, max-cx commented on modules/administration-guide/nav.adoc
> +** xref:migration-to-external-database-setup.adoc[]
```suggestion
** xref:migration-to-an-external-database-setup.adoc[]
```

2022-10-17 09:16 UTC, max-cx commented on modules/administration-guide/nav.adoc
>  * xref:migration-from-postgresql-9-to-postgresql-13.adoc[]
```suggestion
* xref:upgrading-postgresql.adoc[]
```

2022-10-17 09:26 UTC, max-cx requested changes
Hi Anatolii, I reviewed the files. If you go through my suggestions and apply those that you agree with, then after that I will clone this branch and review and preview this PR locally to make any remaining edits, and then you will see/approve my final changes when I open a PR to your branch.

2022-10-26 08:11 UTC, max-cx commented
I committed/applied some of my minor suggestions (like adding `the` and `$`) to save Anatolii's effort and time reviewing my suggested changes.

2022-11-30 15:03 UTC, max-cx commented
Closing this PR after discussing it with @tolusha.

2022-11-30 15:03 UTC, closed without merging