fix: broken link
eclipse-che/che-docs pull request #2185
Opened 2021-12-07 18:33 UTC by themr0c

Fix a broken link

2021-12-08 13:22 UTC, max-cx commented on modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
> +This document assumes that {prod} must be configured to run on following domain: `++http://che.aws.my-ide.cloud++`.
```suggestion
This document assumes that {prod} must be configured to run on the following domain:
+
`++http://che.aws.my-ide.cloud++`
```

2021-12-08 13:24 UTC, max-cx requested changes
This might make it a bit clearer.

2021-12-08 13:24 UTC, max-cx commented on modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
> +This document assumes that {prod} must be configured to run on following domain: `++http://che.aws.my-ide.cloud++`.
```suggestion
This document assumes that {prod} must be configured to run on the following domain:
+
`++http://che.aws.my-ide.cloud++`
```

2021-12-08 13:26 UTC, benoitf approved these changes

2021-12-09 15:27 UTC, rkratky approved these changes

2021-12-09 16:19 UTC, merged