Adding a list of supported languages
eclipse-che/che-docs pull request #2414
Opened 2022-08-02 14:35 UTC by deerskindoll

## What does this pull request change?
Adding a list of supported languages to the user guide.

## What issues does this pull request fix or reference?
https://issues.redhat.com/browse/RHDEVDOCS-4164

## Specify the version of the product this pull request applies to
Dev Spaces 3.0, 3.1

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/main/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

2022-08-02 16:27 UTC, rkratky requested changes
@deerskindoll, comments added.

2022-08-02 16:27 UTC, rkratky commented on modules/end-user-guide/partials/ref-supported-languages.adoc
> +Following table lists languages supported by {prod-short}.
```suggestion
```

2022-08-02 16:27 UTC, rkratky commented on modules/end-user-guide/nav.adoc
> +** xref:supported-languages.adoc[]
Such file (`supported-languages.adoc`) doesn't exist (the PR doesn't add it), so the link cannot work. In order for it to work, add a `supported-languages.adoc` file into the `pages/` directory.

2022-08-02 16:27 UTC, rkratky commented on modules/end-user-guide/partials/ref-supported-languages.adoc
> +[id="supported-languages_{context}"]
This file needs to be in the `pages/` directory, and it must be called `supported-languages.adoc`.

2022-08-03 12:08 UTC, deerskindoll commented on modules/end-user-guide/partials/ref-supported-languages.adoc
> +[id="supported-languages_{context}"]
I see. I tried moving it to the pages folder but because I didn't rename it, it didn't work for obvious reasons.

2022-08-04 12:08 UTC, rkratky approved these changes

2022-08-04 12:09 UTC, merged

2022-08-18 12:25 UTC, l0rd commented
@rkratky @themr0c Eclipse Che is not directly supporting languages anymore. We are supporting IDEs (VS Code, Theia, IntelliJ, PyCharm) and each IDE has a list of languages that it supports. That means that Eclipse Che supports thousands of languages and what is listed here is just a list of source code examples that we include in Che. How can we update that languages list so that it makes more sense for Che?

2022-08-18 12:25 UTC, l0rd commented
cc @Kasturi1820