Updated docs for jdt.ls integration
eclipse-che/che-docs pull request #404
Opened 2018-05-10 18:11 UTC by JPinkney

Signed-off-by: jpinkney <josh.pinkney@mail.utoronto.ca>

Updated documentation for jdt.ls integration in all applicable places (that I could find)

*Shouldn't be merged until 5730_java_ls_poc branch is merged in master to avoid confusion*

2018-05-10 18:58 UTC, ghost approved these changes

2018-05-11 08:40 UTC, tsmaeder submitted a review, later dismissed
ltgm

2018-05-11 08:41 UTC, tsmaeder commented
We must not merge this one until branch 5730_java_ls_poc is merged.

2018-05-11 08:43 UTC, tsmaeder requested changes
ltgm, but wait until we merge branch 5730_java_ls_poc

2018-05-14 23:00 UTC, slemeur approved these changes

2018-10-17 13:04 UTC, tsmaeder approved these changes

2018-10-17 13:16 UTC, merged