[WIP] Topic open shift admin guide
eclipse-che/che-docs pull request #490
Opened 2018-09-14 23:15 UTC by petra-sargent

### What does this PR do?
This PR updates the style and grammar for OpenShift - Admin Guide, found here: https://www.eclipse.org/che/docs/openshift-admin-guide.html

### What issues does this PR fix or reference?
#489

2018-09-14 23:19 UTC, petra-sargent commented
@rkratky @eivantsov  Please review my update.  I am fixing grammar errors and updating the style of the Admin Guide. I want to make sure that I am not changing the technical  meaning when I update the sentence structure. Thanks!

2018-09-17 20:37 UTC, slemeur approved these changes

2018-09-18 14:04 UTC, rkratky requested changes
Many issues in the file; end of file untouched.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All examples use `kubectl` command. OpenShift administrators should use `oc`
Missing period.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== RAM Prerequisites
P shouldn't be capital (see CCS guidelines for titles -- use sentence case, not title case).

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Che server pod uses up to 1 GB RAM. The initial request for RAM is 256 MB. The Che server pod rarely uses more than 800 MB RAM.
"of RAM"?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +You must have at least 5 GB of RAM to run multi-user Che. The Keycloak authorization server and Postgres database require the extra RAM. Multi-user Che uses RAM in this distribution:
Postgres is slang. Use PostgreSQL.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Postgres: approximately 515 MB
-> PostgreSQL

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Requirements for Resource Allocation and Quotas
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Setting up the Project Workspace
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Setting Up A Single OpenShift Project*
This should be a section title.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Procedure
Is this necessary? (We're not using the modular templates here.)

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +`CHE_OPENSHIFT_SERVICEACCOUNTNAME`.
Why the line break?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  # eclipse-che is Che namespace
This is unclear because it looks like a command run by root, not necessarily a comment. I suggest taking the comment out of the block and making it a part of the surrounding explanation.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Setting up a Multi OpenShift Project*
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Procedure
Necessary?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. To create workspace objects in different namespaces for each user, set NULL_CHE_INFRA_OPENSHIFT_PROJECT to NULL
Enclose the variable and literal value in backticks.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. To create resources on behalf of the currently logged-in user, use user’s OpenShift tokens to create resources.
Repetitive: "To create resources ... to create resources".

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== How the Che Server Uses PVCs and PVs for Storage
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Che server, Keycloak, Postgres, and workspace pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with https://kubernetes.io/docs/concepts/storage/persi
-> PostgreSQL

* 'yamls' is slangy; use 'YAML files'

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Storage Requirements for Che Infrastructure
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The storage requirements for Che infrastructure:
Given the section title, this sentence seems redundant.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Keycloak: 2 PVCs, 1 GB each to store logs and Keycloak data
Lists should be consistent in either using or not using periods.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Postgres needs one 1 GB PVC to store database
-> PostgreSQL

* "1GB PVC" -- does it need PVCs sized 1 GB, or 1 GB of PVCs?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Storage Strategies for Che Workspaces
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Like the Che workspace PVC access type and claim size, the workspace PVC strategy is configurable:
"Like the Che workspace PVC access type and claim size," -- redundant?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +|*common* |
This table is misformatted. Each row must have the same number of columns. Build locally to preview. The row  starting with 'common' has been mangled by the edit.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Unique PVC Strategy
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*How the Common PVC Strategy Works*
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All workspaces use the same PVC to store data declared in their volumes (projects and workspace-logs by default and whatever additional link:volumes[volumes] that a user can define.)
Why dash in workspace-logs?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +A PV that is bound to PVC, `che-claim-workspace`, will have the following structure:
I don't think the commas should have been added.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Volumes can be anything that a user defines as volumes for workspace machines (volume name == directory name in `${PV}/${ws-id}`).
== should be substituted with "is", "means", "is equal to", or some such.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Enabling a Common Strategy*
* Sentence case.
* Should be a section title.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +If you have already deployed Che with unique strategy
Colon at the end, or perhaps a comma and no line break?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Set `CHE_INFRA_KUBERNETES_PVC_STRATEGY` to `common` in dc/che
* What's 'dc/che'? The term should be qualified.
* Missing period.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +If applying che-server-template.yaml
Colon at the end, or perhaps a comma and no line break?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Pass `-p CHE_INFRA_KUBERNETES_PVC_STRATEGY=common` to oc new-app command.
As a command, 'oc new-app' should be in backticks.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Note:
Is it an admonition? It should be formatted as such.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. Pre 1.6 Kubernetes, you need to set `CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS` to `true`.
-> "In Kubernetes older than 1.6, ..."

* 'to set the ........... variable to ...'

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. In Kubernetes 1.6 and higher, setting this variable to true is not a requirement.
'true' in backticks.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Restrictions on using Common PVC Strategy*
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +When a common strategy is used, and a workspace PVC access mode is RWO, only one Kubernetes node can simultaneously use PVC.  If there are several nodes, a common strategy can still be used, but in t
* 'only one node simultaneously' -- doesn't make sense; if it' just one, then there's nothing simultaneous about it
* the whole para is very wordy; why not split it up to 'one node' and 'several nodes'?
* don't use 'i.e.' in docs
* don't use 'in fact' and 'have luck' in docs
* 'by passing the ................ environment variable'
* che -> Che

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Another restriction is that only pods in the same namespace can use the same PVC, thus, `CHE_INFRA_KUBERNETES_PROJECT` env variable should not be empty - it should be either Che server namespace (in
* 'the ........ environment variable'
* env -> envirnment
* in this case, ...
* che -> Che
* what's SA? Term should be quallified.
* don't use slash in docs; use 'or' or 'and'
* needs to be...

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +== Updating Your Che Deployment
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To update  Che deployment:
a Che deployment?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +You can change the image tag either
The following text doesn't go well after 'either'.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Manually: `kubeclt edit dc/che`
* List is inconsistent. Perhaps change "Manually:" into "Execute"?
* Missing period.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Change in OpenShift web console: > deployments > edit yaml > image:tag
* 'the OpenShift web console'
* no '>' after colon
* GUI elements in bold
* missing period

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Define the image tags with docker: `kubectl set image dc/che che=eclipse/che-server:${VERSION} --source=docker`
* missing period
* 'using the Docker service'

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. Update Keycloak and Postgres deployments (optional):
-> PostgreSQL

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  You can get the list of available versions at https://github.com/eclipse/che/tags[Che GitHub page].
-> at the Che...

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* add  `--set cheImagePullPolicy=IfNotPresent` to link:openshift-multi-user[Che deployment].
-> 'the Che deployment'

* Capitalize start of sentence.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To change the pull policy, either
'... policy, do one of the following:'

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* manually edit `dc/che` after deployment
* Capitalize start of sentence, put period behind.
* Qualify 'dc/che'.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To delete data or request the admininistrator to delete data, do this command with the user or adminstrator token:
do -> run

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  curl -X DELETE http://che-server/api/user/{id}
Add dollar sign?

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  == Debug Mode
Sentence case.

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To run Che Server in debug mode, set the following environment variable in Che deployment to true (default is false):
* 'the Che deployment'
* true and false in backticks

2018-09-18 14:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To run Che Server in debug mode, set the following environment variable in Che deployment to true (default is false):
Rest of the file is untouched, but it also needs many fixes.

2018-09-19 14:44 UTC, petra-sargent commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All examples use `kubectl` command. OpenShift administrators should use `oc`
Updated

2018-09-19 15:20 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All examples use `kubectl` command. OpenShift administrators should use `oc`
@petra-sargent No need to reply 'updated' if you agree with the comment. Instead, just push a commit that does the update, and the new doc will appear here.

2018-09-19 15:21 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All examples use `kubectl` command. OpenShift administrators should use `oc`
Btw, I overlooked:

-> 'the kubectl command'
-> 'the oc command'

2018-09-19 20:15 UTC, petra-sargent commented
Thanks @rkratky, I think I updated most of your recommendations;@eivantsov  - can you recommend a developer(s) who would be able to review the Admin guide?

2018-09-22 04:26 UTC, ghost commented
@petra-sargent I'd be the one who reviews

I can see some conflicts, can you please resolve those? Thanks

2018-09-30 15:22 UTC, rkratky requested changes
Many more corrections needed.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +All examples use `the kubectl command'. OpenShift administrators should use `the oc command`.
Only the command itself (kubectl, oc) should be in backticks. Also, careful that you use backticks, not regular apostrophes.

Always build and preview the docs locally to make sure the changes you're about to commit render correctly.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Multi-User*
Why is this not a section heading?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Setting Up A Single OpenShift Project*
Why is this not a section heading? Also, please, use sentence case.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Procedure
Please, explain why this is necessary.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Note
Is this supposed to be an admonition? If so, `NOTE:` needs to be used. However, I don't think an admonition is warranted here.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Eclipse-che is Che namespace
If this is meant to explain a part of the preceding command, then it needs to be:

In the command above, `eclipse-che` is the Che namespace.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Setting up a multi OpenShift project*
Why is this not a section heading?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Procedure
Please, explain why this is necessary.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. To create workspace objects in different namespaces for each user, set `NULL_CHE_INFRA_OPENSHIFT_PROJECT to NULL`
-> `NULL_CHE_INFRA_OPENSHIFT_PROJECT` to `NULL`
-> missing period

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. To create resources on behalf of the currently logged-in user, use user’s OpenShift tokens.
-> the user's

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +|*common* |
Please, use ` +` to force line breaks. See https://asciidoctor.org/docs/user-manual/#line-breaks

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +|easy to manage and control storage
Unify table contents to either start with caps, or not.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +no need to recycle PVs when pod with pvc is deleted |ws pods should all be in one namespace
ws -> workspace

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Set `CHE_INFRA_KUBERNETES_PVC_STRATEGY` to `common` in dc/che.
Qualify 'dc/che'.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +If applying che-server-template.yaml:
Use fixed-width font for file names.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Pass `-p CHE_INFRA_KUBERNETES_PVC_STRATEGY=common` to `oc new-app` command.
-> the `oc new-app` command

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. Pre 1.6 Kubernetes, you need to set `CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS` to `true`.
-> For Kubernetes older then 1.6

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. In Kubernetes 1.6 and higher, setting this variable to true is not a requirement.
-> `true`

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +*Restrictions on using Common PVC Strategy*
Why is this not a section heading?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +When a common strategy is used, and a workspace PVC access mode is RWO, only one Kubernetes node can simultaneously use PVC.  If there are several nodes, a common strategy can still be used, but in t
* Do not use 'ie' in docs. See IBM Style Guide.
* Use formal language, not _'in fact, you may sometimes have some luck`_.
* -> by passing the `CHE_INFRA_KUBERNETES_PVC_ACCESS_MODE=ReadWriteMany` environment variable
* -> the Che deployment

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To update  Che deployment:
Redundant?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Another restriction is that only pods in the same namespace can use the same PVC, thus, `CHE_INFRA_KUBERNETES_PROJECT` environment variable should not be empty - it should be either Che server namesp
* -> in this case, objects
* che -> Che
* qualify or expand 'SA'
* don't use slash in docs

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The default pull policy is Always. The default tag is `nightly`. This tag sets the image pull policy to Always and triggers a new deployment with a newer image, if available.
-> `Always`

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  == Che Server Logs
Sentence case, please.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * `kubectl describe pvc che-data-claim`, find PV it is bound to, then `oc describe pv $pvName`, you will get a local path with logs directory. Be careful with permissions for that directory, since on
* First sentence awkward stylistically.
* What does it mean _'be careful with permissions'_? Be specific.
* Don't use contractions (_wont_).
* Missing period.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * `kubectl get log dc/che`
Expand to say, e.g.:

Run the `kubectl get log dc/che` command.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * `kubectl describe pvc che-data-claim`, find PV it is bound to, then `oc describe pv $pvName`, you will get a local path with logs directory. Be careful with permissions for that directory, since on
Line 226:

* Cap letter to start sentence.
* -> the Kubernetes web console
* mark up 'eclipse-che'
* Finish the sentence (what should be done once the user navigates to *pods > che-pod > logs*?).

Line 228:

* Multiple language mistakes

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* If your infrastructure does not support workspace recovery, all running workspaces are forcibly stopped;
; -> .

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* If your infrastructure does support workspace recovery, any workspaces that are currently starting or stopping is allowed to finish that process. Running workspaces do not stop.
is -> are

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +If you want a full shutdown with workspaces stopped, you can request this by using the `shutdown=true` parameter. When preparation process is finished, the `READY_TO_SHUTDOWN` state is set which allo
*  -> the preparation process
* -> set, which
* -> to stop the current

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  == Che Master States
Sentence case.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The Che Master has three possible states:
Why capitalized 'Master'?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The `PREPARING_TO_SHUTDOWN` state means that no new workspace startups are allowed. This situation can cause two different results:
startups -> starts

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The default grace termination period of Kubernetes/OpenShift workspace’s pods is '0'.  This setting terminates pods almost instantly and significantly decreases the time required for stopping a works
* Don't use slash.
* Don't use possessive with inanimate nouns.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  == Che Workspace Termination Grace Period
Sentence case.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +If the `terminationGracePeriodSeconds` have been explicitly set in the Kubernetes/OpenShift recipe, this environment variable does not override the recipe.
* -> the `terminationGracePeriodSeconds` parameter has been
* Don't use slash.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  *IMPORTANT!*
Use proper admonition mark up.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Recreate update
Convert to a table.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Prerequisites
-> .Prerequisites
-> .Procedure

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * Make POST request to the /api/system/stop api to start WS master suspend (means that all new attempts to start workspaces will be refused, and all current starts/stops will be finished). Note that
* Mark up POST.
* Mark up /api/system/stop
* api -> API
* WS -> workspace
* means -> this means
* don't use slash
* admin -> administrator

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Make periodical GET requests to /api/system/state api, until it returns READY_TO_SHUTDOWN state. Also, you can check for "System is ready to shutdown" in the server logs.
* mark up GET
* mark up /api/system/state
* api -> API
* no comma before 'until'
* mark up READY_TO_SHUTDOWN

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +=== Performing a Rolling Update
Sentence case.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Prerequisites
-> .Prerequisites
-> .Procedure

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Ensure there is full API compatibility between new master and old ws agent versions, as well as database compatibility (since it is impossible to use DB migrations on this update mode);
* Expand 'ws'.
* Expand 'DB'.
* ; -> .

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Set the deployment update strategy set to Rolling;
; -> .

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Ensure `terminationGracePeriodSeconds` deployment parameter has enough value (see details below).
* -> Ensure the terminationGracePeriodSeconds` deployment parameter
* What's _'enough value'_?
* Where _'below'_?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Press Deploy button or execute `oc rollout latest che` from cli client.
* -> the Deploy button
* mark up 'Deploy'
* cli client -> the CLI client

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * Some users may experience problems with websocket reconnections or missed events published by WebSocket connection(when a workspace is STARTED but dashboard displays that it is STARTING); Need to r
Lines 310 and 311 contain numerous language and mark up mistakes.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  If new version of Che server contains some DB migrations, but there is still API compatibility between old and new version, recreate update type may be used, without stopping running workspaces.
* -> a new version
* expand DB
* -> the old and the new versions
* -> the Recreate update type
* mark up Recreate?

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To remove all Keycloak related objects
* -> Keycloak-related
* missing colon

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To remove all PostgreSQL related objects
* -> PostgreSQL-related
* missing colon

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +PVCs, service accounts and role bindings should be deleted separately because `oc delete all` does not delete them.
Use serial comma.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To delete Che server PVC, ServiceAccount and RoleBinding:
* Use serial comma.
* Missing colon.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +To delete Keycloak and PostgreSQL PVCs
Missing colon.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  * link:#che-configuration[configure] Che to use this Keycloak identity provider in order to retrieve the OpenShift tokens of Che users.
configure -> Configure

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  Once this is done, every interactive action done by a Che user on workspaces, such as start or stop, will create OpenShift resources under his personal OpenShift account. And the first time the user
Use gender-neutral pronouns.

2018-09-30 15:22 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
>  Once this is done, every interactive action done by a Che user on workspaces, such as start or stop, will create OpenShift resources under his personal OpenShift account. And the first time the user
Lines >371 are untouched even though they contain numerous grammar and mark up mistakes. Please, review and fix the rest of the file, too.

2018-10-07 07:03 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Every workspace action such as start or stop creates an OpenShift resource in the OpenShift user account.  A notification message displays which allows you to link the Keycloak account to your OpenSh
* suggest leaving commas around 'such as start or stop'
* _'A notification message displays which allows'_ -- displays what? Perhaps use "A notif. msg instructs the user to..." or similar.

2018-10-07 07:04 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +The default grace termination period of Kubernetes/OpenShift workspace’s pods is '0'.  This setting terminates pods almost instantly and significantly decreases the time required for stopping a works
* no slash, please
* no need for possessive in _'period of Kubernetes/OpenShift workspace’s pods'_

2018-10-07 07:06 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +When the certificate is self-signed or is not trusted, use the enivronment variable `OPENSHIFT_IDENTITY_PROVIDER_CERTIFICATE` to pass the OpenShift console certificate to the Keycloak deployment. Thi
* typo: enivronment
* better word order: "use the `OPENSHIFT_IDENTITY_PROVIDER_CERTIFICATE` environment variable"

2018-10-07 07:12 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +But for non-interactive workspace actions, such as workspace stop on idling or Che server shutdown, the dedicated OpenShift account configured for the Kubernetes infrastructure is used. See link:admi
* incorrect URL; should be `openshift-admin-guide.html#who-creates-workspace-objects`
* "AdminGuide" -> "Setting up the project workspace"

2018-10-12 19:29 UTC, petra-sargent commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Set `CHE_INFRA_KUBERNETES_PVC_STRATEGY` to `common` in dc/che
I'm not sure

2018-10-16 15:15 UTC, closed without merging

2018-10-16 15:17 UTC, petra-sargent commented
This PR is reopened as https://github.com/eclipse/che-docs/pull/518.

2018-10-16 15:19 UTC, rkratky commented
@petra-sargent Please, remove the WIP from the title.