This fixes any grammar and syntax errors for Openshif-Admin Guide
eclipse-che/che-docs pull request #518
Opened 2018-10-15 20:28 UTC by petra-sargent

Signed-off-by: Petra Sargent <psargent@redhat.com>

### What does this PR do?
This updates grammar and style errors. 

### What issues does this PR fix or reference?
#489

2018-10-15 20:29 UTC, petra-sargent commented
@rkratky Please review. Thanks!

2018-10-17 15:25 UTC, rkratky requested changes
@petra-sargent  I'm only half-way through, but I'm giving up with the review. This PR contains many mistakes that have already been pointed out in previous reviews. Please, fix them first.

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Make periodical GET requests to /api/system/state api, until it returns READY_TO_SHUTDOWN state. Also, you can check for "System is ready to shutdown" in the server logs.
```suggestion
* Make periodical `GET` requests to the `/api/system/state` API, until it returns the `READY_TO_SHUTDOWN` state. Also, you can check for `System is ready to shutdown` in the server logs.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +[id="ram-prerequisites"]
@petra-sargent, did you check the whole body of docs for occurrences of the anchors you modified or removed?

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. For pre 1.6 Kubernetes, you need to set the `CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS` variable to `true`.
Don't know why you removed the pass-through macros, but they need to be there. Please, be sure to always check locally-built docs to spot such things (incorrect rendering without the macro).

```suggestion
. For pre 1.6 Kubernetes, you need to set the `pass:[CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS]` variable to `true`.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Update `CHE_INFRA_KUBERNETES_POD_TERMINATION__GRACE__PERIOD__SEC`
```suggestion
* Update `pass:[CHE_INFRA_KUBERNETES_POD_TERMINATION__GRACE__PERIOD__SEC]`.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +* Set the `CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER` environment variable to the alias of the OpenShift identity provider specified in step 1 of its link:#openshift-identity-provider-registratio
```suggestion
* Set the `pass:[CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER]` environment variable to the alias of the OpenShift identity provider specified in step 1 of its link:#openshift-identity-provider-registration[registration in Keycloak]. The default value is `openshift-v3`.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +When the certificate is self-signed or is not trusted, use the enivronment variable `OPENSHIFT_IDENTITY_PROVIDER_CERTIFICATE` to pass the OpenShift console certificate to the Keycloak deployment. Thi
```suggestion
When the certificate is self-signed or is not trusted, use the `OPENSHIFT_IDENTITY_PROVIDER_CERTIFICATE` environment variable to pass the OpenShift console certificate to the Keycloak deployment. This will enable the Keycloak server to add the certificate to the list of trusted certificates.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +Keycloak can not contact the OpenShift console to retrieve linked tokens when the certificate used by the OpenShift console is self-signed or is not trusted.
```suggestion
Keycloak cannot contact the OpenShift console to retrieve linked tokens when the certificate used by the OpenShift console is self-signed or is not trusted.
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +. Use the following settings in the link:user-management#auth-and-user-management[Keycloak administration console]:
```suggestion
. Use the following settings in the link:user-management.html#auth-and-user-management[Keycloak administration console]:
```

2018-10-17 15:25 UTC, rkratky commented on src/main/pages/setup-openshift/openshift-admin-guide.adoc
> +But for non-interactive workspace actions, such as workspace stop on idling or Che server shutdown, the dedicated OpenShift account configured for the Kubernetes infrastructure is used. See link:admi
```suggestion
But for non-interactive workspace actions, such as workspace stop on idling or Che server shutdown, the dedicated OpenShift account configured for the Kubernetes infrastructure is used. See link:#setting-up-the-project-workspace[Setting up the project workspace] for more information.
```

2018-11-05 11:31 UTC, rkratky approved these changes

2018-11-05 11:32 UTC, merged