[WIP] Topic workspace overview
eclipse-che/che-docs pull request #519
Opened 2018-10-16 14:35 UTC by petra-sargent

### What does this PR do?
This PR fixes style and grammar errors. 

### What issues does this PR fix or reference?
#507

2018-10-16 14:38 UTC, petra-sargent commented
@rkratky @robin-owen @preetic  Please review. Thank you.

2018-10-16 17:58 UTC, rkratky requested changes

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +A workspace is usually termed as a local directory with projects and meta-information that the integrated development environment (IDE) uses to configure projects. In Eclipse Che, a workspace is the
local host -> localhost

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +The workspace runtime environment is a set of machines where each machine is defined by a recipe. The environment is healthy when all the machines successfully start up and the installers execute job
* start up -> start (don't use phrasal verbs)
* The environment and infrastructure validates a recipe. -> The environment and underlying infrastructure validate a recipe.

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +The runtime environment has a minimum of one machine that can be a Docker container or a Kubernetes pod. You can create multi-machine environments with as many machines as your project infrastructure
Docker container -> Docker-formatted container

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +* single Docker image
Docker image -> container image

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +* Docker file
-> Dockerfile (see https://docs.docker.com/get-started/part2/#define-a-container-with-dockerfile)

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +The bootstrapper starts the installer script after the first process is executed in the machine following the `CMD` or `ENTRYPOINT`.   The role of the bootstrapper is to start the installer scripts w
* the `CMD` or `ENTRYPOINT` -> the `CMD` or `ENTRYPOINT` instructions
* tiny -> small

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
>  == What’s Next?
no contractions

2018-10-16 17:58 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +link:creating-starting-workspaces.html[Create and start your first workspace], learn how to define link:volumes.html[volumes] and link:env-variables.html[environment variables].
comma splice

2018-10-17 13:51 UTC, rkratky requested changes

2018-10-17 13:51 UTC, rkratky commented on src/main/pages/workspace-admin/what-are-workspaces.adoc
> +== What is Next?
sentence case, please :)

2018-10-17 14:27 UTC, rkratky commented
Thanks @petra-sargent.

@eivantsov, @slemeur, please merge when convenient.

2018-10-17 14:32 UTC, slemeur approved these changes

2018-10-17 14:32 UTC, merged