RHDEVDOCS-875: Reviewed the Single-User: Deployment to Kubernetes sec…
eclipse-che/che-docs pull request #534
Opened 2018-10-24 06:38 UTC by supriya-bharadwaj

…tion for language and asciidoc syntax.

Signed-off-by: Supriya Takkhi <sbharadw@redhat.com>

### What does this PR do?
Fixes lang. and markup issues in ** Che on Kubernetes -> Single-User: Deploy to Kubernetes**.
File name: `src/main/pages/setup-kubernetes/kubernetes-single-user.adoc`

Hi @rkratky , can you please review the PR? Thanks!

2018-10-24 10:29 UTC, robin-owen commented on src/main/pages/setup-kubernetes/kubernetes-single-user.adoc
> +== Supported Kuberentes flavors and versions
Typo: Kubernetes

2018-10-24 10:29 UTC, robin-owen commented on src/main/pages/setup-kubernetes/kubernetes-single-user.adoc
> +The single-user deployment to Kubernetes is tested only on MiniKube v0.25 with the *VirtualBox* and *kvm2* VM providers.
"MiniKube" should be "Minikube". This applies globally (I see three instances of "MiniKube" being used in the diff here).

Also, Minikube uses `docker-machine` driver plug-ins to provide functionality for hypervisors. I'd recommend changing "providers" to "drivers" or "driver plug-ins".

2018-10-30 14:00 UTC, supriya-bharadwaj commented
Hi @rkratky , I have incorporated Robin's feedback in this PR. I think it is ready to be merged. Can you have a look, please? Thanks!

2018-11-01 15:09 UTC, rkratky requested changes

2018-11-01 15:09 UTC, rkratky commented on src/main/pages/setup-kubernetes/kubernetes-single-user.adoc
> +title: "Single-User&#58 Deployment to Kubernetes"
Should be consistent with multi-user: https://github.com/eclipse/che-docs/pull/536/files

2018-11-02 08:26 UTC, supriya-bharadwaj commented
HI @rkratky , I have changed the name of the file to make it consistent with the multi-user one. I guess this one is now ready to be merged. Thanks!

2018-11-02 09:12 UTC, rkratky commented
@supriya-bharadwaj, it's not about the file nme but about the heading:  "Deploying multi-user Che to Kubernetes".

2018-11-02 09:28 UTC, supriya-bharadwaj commented
@rkratky , yeah, I changed the heading to "Deploying single-user Che to Kubernetes". I should have added exactly that in my comment.

2018-11-02 10:05 UTC, rkratky approved these changes

2018-11-02 10:05 UTC, merged