Add more information about manageSystem permission
eclipse-che/che-docs pull request #549
Opened 2018-11-01 07:52 UTC by mkuznyetsov

### What does this PR do?
Add more information about manageSystem:
- list of available services
- Admin initialization

### What issues does this PR fix or reference?

2018-11-01 08:20 UTC, skabashnyuk commented on src/main/pages/user-management/permissions.adoc
> +User with `manageSystem` are able to perform various admin operations.
A user with `manageSystem` permission

2018-11-01 08:20 UTC, skabashnyuk commented on src/main/pages/user-management/permissions.adoc
> +On Start, Che will grant this permission to the admin user, with default name `admin`.
On che-master start or after the first login, this permission will be granted to the person configured with ```CHE_SYSTEM_ADMIN__NAME``` property.

2018-11-01 08:20 UTC, skabashnyuk commented on src/main/pages/user-management/permissions.adoc
> +|/logger/{name}|POST | Add new logger
More info about logger. What, why, how?

2018-11-01 13:24 UTC, mkuznyetsov commented on src/main/pages/user-management/permissions.adoc
> +User with `manageSystem` are able to perform various admin operations.
rewrote that part

2018-11-01 13:24 UTC, mkuznyetsov commented on src/main/pages/user-management/permissions.adoc
> +On Start, Che will grant this permission to the admin user, with default name `admin`.
rewrote that part

2018-11-01 13:24 UTC, mkuznyetsov commented on src/main/pages/user-management/permissions.adoc
> +|/logger/{name}|POST | Add new logger
fixed

2018-11-02 07:09 UTC, skabashnyuk approved these changes
other looks good to me

2018-11-02 07:09 UTC, skabashnyuk commented on src/main/pages/user-management/permissions.adoc
> +All system permissions will be granted to the admin user configured with CHE_SYSTEM_ADMIN__NAME property (default `admin`).
to the user configured

2018-11-02 13:53 UTC, skabashnyuk commented on src/main/pages/developer-guide/logging.adoc
> +will add logger level configuration that will set DEBUG level for loggers in `org.eclipse.che.api.workspace.activity` package
will change logger level

2018-11-05 17:06 UTC, rkratky requested changes

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +E.g., sending PUT request with following configuration
```suggestion
For example, sending PUT request with following configuration
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +will add logger level configuration that will set DEBUG level for loggers in `org.eclipse.che.api.workspace.activity` package
```suggestion
adds logger level configuration that sets the `DEBUG` level for loggers in the `org.eclipse.che.api.workspace.activity` package.
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +All system permissions will be granted to the admin user configured with CHE_SYSTEM_ADMIN__NAME property (default `admin`).
```suggestion
All system permissions will be granted to the administration user configured with the pass:[`CHE_SYSTEM_ADMIN__NAME`] property (the default is `admin`).
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +This will happen at Che Server start, or if he is not present in Che user database, after his first login.
```suggestion
This happens at Che Server start. If the user is not present in the Che user database, it happens after the user's login.
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +Users with `manageSystem` persmission will have access to the following services:
```suggestion
Users with the `manageSystem` permission have access to the following services:
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/logger/{name}|GET | Get configurations of logger by it's name in Che Server
```suggestion
|`/logger/{name}` |GET | Get configurations of logger by its name in Che Server
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/logger/{name}|PUT | Create Logging in Che Server
```suggestion
|/logger/{name}|PUT | Create logging in Che Server
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/logger/{name}|POST | Edit Logging in Che Server
```suggestion
|`/logger/{name}` |POST | Edit logging in Che Server
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/resource/free/ |GET | Get free resource limits
```suggestion
|`/resource/free/` |GET | Get free resource limits
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/resource/free/{accountId} |GET | Get free resource limits for given account
```suggestion
|`/resource/free/{accountId}` |GET | Get free resource limits for given account
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/resource/free/{accountId} |POST | Edit free resource limit for given account
```suggestion
|`/resource/free/{accountId}` |POST | Edit free resource limit for given account
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/resource/free/{accountId} |DELETE | Remove free resource limit for given account
```suggestion
|`/resource/free/{accountId}` |DELETE | Remove free resource limit for given account
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/installer/ |POST | Add installer to the registry
```suggestion
|`/installer/` |POST | Add installer to the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/installer/{key} |PUT | Update installer in the registry
```suggestion
|`/installer/{key}` |PUT | Update installer in the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/installer/{key} |DELETE | Remove installer from the registry
```suggestion
|`/installer/{key}` |DELETE | Remove installer from the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/logger/ |GET | Get logging configurations in Che Server
```suggestion
|`/logger/` |GET | Get logging configurations in Che Server
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/resource/{accountId}/details |GET | Get detailed information about resources for given account
```suggestion
|`/resource/{accountId}/details` |GET | Get detailed information about resources for given account
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/system/stop |POST | Shutdown all system services, prepare Che to stop
```suggestion
|`/system/stop` |POST | Shutdown all system services, prepare Che to stop
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/stacks |All methods | All Stack service methods
```suggestion
|`/stacks` |All methods | All Stack service methods
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +A Super Privileged mode can be enabled to extend with additional services.
To extend what?

```suggestion
A super-privileged mode can be enabled to extend with additional services.
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +To enable it, configure environment variable `CHE_SYSTEM_SUPER_PRIVILEGED_MODE=true` in the `che.env` file.
```suggestion
To enable it, configure the `CHE_SYSTEM_SUPER_PRIVILEGED_MODE=true` environment variable in the `che.env` file.
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +List of services that will be enabled for users with `manageSystems` permissions and Super Priviliged Mode on:
```suggestion
List of services that are enabled for users with `manageSystems` permissions and with super-privileged mode on:

```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/workspace/namespace/{namespace:.*} |GET |Get all workspaces for given namespace.
```suggestion
|`/workspace/namespace/{namespace:.*}` |GET |Get all workspaces for given namespace.
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/workspace/{id} |DELETE |Stop workspace
```suggestion
|`/workspace/{id}` |DELETE |Stop workspace
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/workspace/{key:.*} |GET | Get workspace by key
```suggestion
|`/workspace/{key:.*}` |GET | Get workspace by key
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/organization/resource/{suborganizationId}/cap |GET |Get resource cap for given organization
```suggestion
|`/organization/resource/{suborganizationId}/cap` |GET |Get resource cap for given organization
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/organization/resource/{suborganizationId}/cap |POST |Set resource cap for given organization
```suggestion
|`/organization/resource/{suborganizationId}/cap` |POST |Set resource cap for given organization
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/organization/{parent}/organizations |GET | Get child organizations
```suggestion
|`/organization/{parent}/organizations` |GET | Get child organizations
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +|/organization |GET | Get user's organizations
```suggestion
|`/organization` |GET | Get user's organizations
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer |GET | Get installers
```suggestion
|`/installer` |GET | Get installers
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer/{id}/version |GET | Get versions of installers by given id
```suggestion
|`/installer/{id}/version` |GET | Get versions of installers by given id
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer/orders |GET | Get installers, ordered by their dependencies
```suggestion
|`/installer/orders` |GET | Get installers, ordered by their dependencies
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer/ |POST | Add installer to the registry
```suggestion
|`/installer/` |POST | Add installer to the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer/{key} |PUT | Update installer in the registry
```suggestion
|`/installer/{key}` |PUT | Update installer in the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +|/installer/{key} |DELETE | Remove installer from the registry
```suggestion
|`/installer/{key}` |DELETE | Remove installer from the registry
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +|GET | logger/ - | get list of all loggers
```suggestion
|GET | `logger/ -` | get list of all loggers
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +|GET | logger/{name} | get info about particular logger
```suggestion
|GET | `logger/{name}` | get info about particular logger
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +|POST | logger/{name} | update logger configuration
```suggestion
|POST | `logger/{name}` | update logger configuration
```

2018-11-05 17:06 UTC, rkratky commented on src/main/pages/developer-guide/logging.adoc
> +|PUT | logger/{name} | create logger configuration
```suggestion
|PUT | `logger/{name}` | create logger configuration
```

2018-11-06 15:06 UTC, mkuznyetsov commented on src/main/pages/user-management/permissions.adoc
> +A Super Privileged mode can be enabled to extend with additional services.
super-privileged mode will enable `manageSystem` permission with access to additional services.

2018-11-06 15:47 UTC, rkratky commented on src/main/pages/user-management/permissions.adoc
> +A Super Privileged mode can be enabled to extend with additional services.
Thanks for the clarification. I suggest to use:

```suggestion
Super-privileged mode can be enabled, which in turn enables the `manageSystem` permission with access to additional services.
```

2018-11-06 15:51 UTC, rkratky approved these changes

2018-11-06 16:19 UTC, merged