[WIP] I585 workspace installers
eclipse-che/che-docs pull request #588
Opened 2018-11-07 19:14 UTC by petra-sargent

### What does this PR do?
This fix grammar and style

### What issues does this PR fix or reference?
#585

2018-11-07 19:14 UTC, petra-sargent commented
@rkratky @robin-owen Please review. Thanks!

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +You can enable or disable installers per machine by using the *User Dsahboard* or by updating the workspace machine configutation. When an installer is enabled, the bootstrapper executes an installer
Two typos: "User Dashboard" and "configuration".

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +Another possible issue can be with permissions to files and folders. For example, an installer may need to write to the https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/cento
Use "directories" instead of "folders".

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +Che installers are stored at the Installer Registry. They can be viewed and edited through the Installer Registry REST API:
Would it be accurate to describe the installers as being stored _in_ the Installer Registry rather than _at_ the Installer Registry?

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +Installers run as if a user in the container has `sudoers` privileges. If the user does not have privileges, the installer fails with `permission denied` issues.
This changes the meaning. In the original text, this is qualified as "may expect" `sudoers` membership.

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +This problem can occur with OpenShift, when a pod is run by an arbitrary user with no permissions to use sudo, or to access or modify resources on the file system.
`sudo` should be styled here.

The comma in "OpenShift, when" is grammatically incorrect.

Also, I don't think "arbitrary" is needed here. We can simply say "a user without permission to use `sudo`".

2018-11-07 20:24 UTC, kowen-rh commented on src/main/pages/workspace-admin/installers.adoc
> +Installers are saved in a configuration file that a link:what-are-workspaces.html#bootstrapper[bootstrapper] uses to execute jobs. An installer script works exactly the same way as other shell script
What configuration file?

"An installer script works exactly the same way as other shell scripts in Linux" doesn't really tell me anything. Why is that important? What user expectation are we trying to confirm here?

2018-11-08 14:34 UTC, petra-sargent commented on src/main/pages/workspace-admin/installers.adoc
> +Che installers are stored at the Installer Registry. They can be viewed and edited through the Installer Registry REST API:
I think it would be"in"

2018-11-08 15:03 UTC, petra-sargent commented on src/main/pages/workspace-admin/installers.adoc
> +Installers are saved in a configuration file that a link:what-are-workspaces.html#bootstrapper[bootstrapper] uses to execute jobs. An installer script works exactly the same way as other shell script
These are great questions for the writer of the document. The focus here is on grammar and style.

2018-11-08 15:09 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +Installers are saved in a configuration file that a link:what-are-workspaces.html#bootstrapper[bootstrapper] uses to execute jobs. An installer script works exactly the same way as other shell script
@petra-sargent, please, file a docs GH issue for this, so that it can be corrected in due course.

2018-11-19 12:04 UTC, rkratky requested changes

2018-11-19 12:04 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +1.  Prepare the environment and download dependencies for a particular software or tool
missing periods in list items

2018-11-19 12:04 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +Some installers activate special agents, such as the workspace, terminal, and exec agents.  If a workspace agent fails to start, the workspace is treated as if it has been started but the IDE is not
* 'exec' agent is slang for execution, or the name of the agent?
* 'commands' is the GUI name of the widget?

* can we be more specific than 'Some'? Can we list available agents and their function?
* the example provided is strange; we should have a list of agents and their properties & what happens when they fail to start & how to fix it

Please, file a bug to fix the last two items.

2018-11-19 12:04 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +Installers run as if a user in the container may have `sudoers` privileges. If the user does not have privileges, the installer fails with `permission denied` issues.
* headline the indiv. failures
* may have -> has
* -> does not have the privileges
* 'issues'? does it actually list some issues, or is it just an 'error message'?

2018-11-19 12:04 UTC, rkratky commented on src/main/pages/workspace-admin/installers.adoc
> +Che installers are stored in the Installer Registry. They can be viewed and edited through the Installer Registry REST API:
The paths (1st column) in the following table should be monospaced, i.e. in backticks.

2018-11-19 22:27 UTC, petra-sargent commented on src/main/pages/workspace-admin/installers.adoc
> +Installers run as if a user in the container may have `sudoers` privileges. If the user does not have privileges, the installer fails with `permission denied` issues.
not sure if issues is just an error message or actually list some issues. I can open up an issue?

2018-11-21 09:27 UTC, rkratky approved these changes

2018-11-21 09:27 UTC, merged