[WIP]I589 Update Workspace ->Volume Mount
eclipse-che/che-docs pull request #595
Opened 2018-11-13 15:07 UTC by petra-sargent

### What does this PR do?

This updates style and grammar.

### What issues does this PR fix or reference?
#589

2018-11-13 15:08 UTC, petra-sargent commented
@rkatky @robin-owen @supriya-bharadwaj  Please review!  Thanks~

2018-11-15 13:24 UTC, petra-sargent commented
@preeticp Please review. Thanks!

2018-11-15 21:14 UTC, robin-owen commented on src/main/pages/workspace-admin/volumes.adoc
> +Your workspace may need additional volumes if your data must persist for a local Maven repository, node_modules folder, ruby jems, or authorized_keys file for SSH connections. You can add additional
Typos/need styling: `node_modules` directory (not folder), Ruby gems, `authorized_keys` file.

2018-11-15 21:14 UTC, robin-owen commented on src/main/pages/workspace-admin/volumes.adoc
> +* The name and path cannot contains special characters, including `-` and `_`.
Typo: "contains" should be "contain"

"including `-` or `_`"

2018-11-19 12:23 UTC, rkratky requested changes

2018-11-19 12:23 UTC, rkratky commented on src/main/pages/workspace-admin/volumes.adoc
> +By default, workspace containers start with a default volume and have a minimum of one PVC that is located in `/projects` directory.
```suggestion
By default, workspace containers start with a default volume and have a minimum of one PVC that is located in the `/projects` directory. 
```

2018-11-19 12:23 UTC, rkratky commented on src/main/pages/workspace-admin/volumes.adoc
> +Your workspace may need additional volumes if your data must persist for a local Maven repository, node_modules folder, ruby jems, or authorized_keys file for SSH connections. You can add additional
+ no 'if'

```suggestion
In order for your data to persist for a local Maven repository, the `node_modules/` directory, Ruby gems, or the `authorized_keys` file for SSH connections, your workspace will need additional volumes. Each machine can add as many volumes as the underlying infrastructure can support. OpenShift may impose a limit on the number of volumes.
```

2018-11-19 12:23 UTC, rkratky commented on src/main/pages/workspace-admin/volumes.adoc
> +* The name and path cannot contains special characters, including `-` and `_`.
```suggestion
* The name and path cannot contain special characters, including dashes (`-`) or underscores (`_`).
```

2018-11-19 12:23 UTC, rkratky commented on src/main/pages/workspace-admin/volumes.adoc
> +If you want your workspace machines to share volumes, create volumes for each machine that has an identical name. This will allow machines to share the same volume.
no 'if'

```suggestion
To allow machines to share the same volume, create a volume for each machine with an identical name. 
```

2018-11-19 12:23 UTC, rkratky commented on src/main/pages/workspace-admin/volumes.adoc
> +* Be sure to use an absolute path.
```suggestion
* Use an absolute path. 
```

2018-11-21 08:50 UTC, rkratky approved these changes

2018-11-21 08:50 UTC, merged