I598 workspace troubleshooting review
eclipse-che/che-docs pull request #599
Opened 2018-11-15 14:07 UTC by supriya-bharadwaj

### What does this PR do?

Fixes lang. and markup issues in *Workspace Troubleshooting -> https://www.eclipse.org/che/docs/workspaces-troubleshooting.html*.
File name: `src/main/pages/workspace-admin/workspaces-troubleshooting.adoc`

Hi @rkratky , can you please review this PR? I'll tag Preeti and Robin for reviewing this PR in the relevant JIRA. Thanks!

2018-11-16 15:57 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +When a workspace is starting, the environment link:recipes.html[recipe] is sent to Docker or to the OpenShift API. The Che server then listens to events provided by a particular infrastructure. In si
I suggest removing "In simple words"

2018-11-16 16:02 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +When a workspace is starting, the environment link:recipes.html[recipe] is sent to Docker or to the OpenShift API. The Che server then listens to events provided by a particular infrastructure. In si
remove the parenthesis for (Docker) -> say something like "container such as Docker " or "Docker container" . Also remove the parenthesis for (OpenShift) -> say something like "OpenShift pod"

2018-11-16 16:13 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* The Docker build fails with the provided `Dockerfile`. This can be because of a broken `Dockerfile` or because of Che. If the Docker build in Che link:recipes.html#dockerfile[does not support conte
I would remove (say, DockerHub) and say something like such as DockerHub

2018-11-16 18:22 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +The Che server, agents running in a workspace container or pod, and the user’s browser communicate with each other. Firewall, filtered ports, and other network restrictions may cause troubles when st
troubles -> trouble

2018-11-16 18:26 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +The Che server, agents running in a workspace container or pod, and the user’s browser communicate with each other. Firewall, filtered ports, and other network restrictions may cause troubles when st
Timeouts: I would recommending removing the colon since a colon is not in the other bullets

2018-11-16 18:33 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +If a workspace start fails because the container or the pod was not launched, you will not see logs from link:installers.html[installers]. Usually, you will find logs from infrastructure, image pull,
Remove etc.  ...Missing a "the"

2018-11-16 19:24 UTC, petra-sargent commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +A workspace is considered to be in a `RUNNING` state after the Che server verifies that the workspace agent is up. The workspace agent also tries to reach the Che server. All this happens in separate
Remove the parenthesis (you may start a workspace using REST API, for example)....

The last sentence seems long... consider breaking it apart and making it a bullet list.  ...the message indicates the following:
* workspace container or pod is up
* workspace agent  has successfully started
* Che server is able to reach the workspace container

2018-11-22 11:24 UTC, rkratky requested changes

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/setup-kubernetes/kubernetes-config.adoc
> +* To open the Che deployment YAML file in the *nano* editor, use the `kubectl edit dc/che` command. The *Vim* editor is used by default.
```suggestion
* To open the Che deployment YAML file in text editor, use the `kubectl edit dc/che` command.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/setup-kubernetes/kubernetes-config.adoc
> +* To update the Che deployment with new environment variables or to modify the values of existing ones, use the `kubectl set env dc/che KEY=VALUE KEY1=VALUE1` command.
```suggestion
* To update the Che deployment with new environment variables or to modify the values of existing ones, use:

----
$ kubectl set env dc/che <key>=<value> <key1>=<value1>
----
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/setup-kubernetes/kubernetes-config.adoc
> +== Changing the unrecoverable events
```suggestion
== Specifying unrecoverable events
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +
```suggestion
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* Environment recipe
```suggestion
* Incorrect environment recipe
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* Network conditions
```suggestion
* Restrictive network settings
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +== Bad recipes
```suggestion
== Incorrect environment recipes
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +When a workspace is starting, the environment link:recipes.html[recipe] is sent to Docker or to the OpenShift API. The Che server then listens to events provided by a particular infrastructure. The C
```suggestion
When a workspace is starting, an environment link:recipes.html[recipe] is sent to Docker or to the OpenShift API. The Che server then listens to events provided by the given infrastructure. The Che server expects a running Docker container or an OpenShift pod. The server fails to start an environment and consequently the starting of the workspace fails if the infrastructure is unable to create and start a container or a pod from the provided recipe.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +A recipe can be bad due to the following reasons:
```suggestion
A recipe can be incorrect due to the following reasons:
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* Installing packages in your Dockerfile instructions can take time. Moreover, in this case you depend on network conditions.
```suggestion
* Installing packages in your `Dockerfile` instructions can take time. This may be influenced by network settings.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +If a workspace start fails because the container or the pod was not launched, you will not see logs from link:installers.html[installers]. Usually, you will find logs from infrastructure, image pull,
```suggestion
=== Viewing logs from a failed workspace start

No link:installers.html[installer] logs are shown when a workspace fails to start because its container or pod are not launched. In most cases, only logs from infrastructure and image pull and build are shown. Analyse these logs to find the problem. The Che server also produces logs that are helpful in debugging the problem.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +== Network conditions
```suggestion
== Restrictive network settings
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +The Che server, agents running in a workspace container or pod, and the user’s browser communicate with each other. Firewall, filtered ports, and other network restrictions may cause trouble when sta
```suggestion
The Che server and agents, which run in a workspace container or pod, and the user’s browser communicate with each other. Firewall, filtered ports, and other network restrictions may cause trouble when starting a workspace.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +A workspace is considered to be in a `RUNNING` state after the Che server verifies that the workspace agent is up. The workspace agent also tries to reach the Che server. All this happens in separate
```suggestion
A workspace is considered to be in a `RUNNING` state after the Che server verifies that the workspace agent is up. The workspace agent also tries to reach the Che server. All this happens in separate containers or pods, and the user’s browser is not yet involved. The `workspace started by user $userName` message in the Che server logs indicates the following:
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
```suggestion
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +
```suggestion
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +It is possible that your browser (the client) cannot connect to a workspace agent. The Che server may use an internal IP to reach the workspace agent, while you may be accessing a workspace from a ma
```suggestion
=== Troubleshooting network setting when workspace agent cannot be reached

An error message saying that the IDE cannot be initialized indicates that the client (browser) cannot reach the workspace agent. This is caused by the Che server using an internal IP address to reach the workspace agent, while you are accessing the workspace from a machine that is located on a different network. To confirm this, open the browser developer console and check failed requests. The failed requests are to `project` and `project-type` API.

To access a workspace from a different network than the one on which the Che server is running, enable access to the ephemeral port range on the Che server network.
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +When a workspace starts, the Che server creates and starts a container or a pod or a set of containers and pods as per the environment recipe. After the container or pod is running, a bootstrapping p
```suggestion
When a workspace starts, the Che server creates and starts a container or a pod or a set of containers and pods as per the environment recipe. After the container or pod is running, a bootstrapping process begins - the bootstrapper binary is downloaded and launched. If the server logs show bootstrapping failures, or you do not see any output in the *Machine* tab of the *Workspaces* view, the reason is that bootstrapper is not downloaded. The following are possible the reasons for the bootstrapper download failure:
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* Network conditions (for example, running firewalld).
```suggestion
* Network conditions (for example, firewall restrictions).
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +* Bad bootstrapper binary URL that the Che server uses (often reproduced when deploying to OpenShift and missing necessary environment variables).
```suggestion
* Incorrect bootstrapper binary URL that the Che server uses (often reproduced when deploying to OpenShift and missing necessary environment variables).
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +Manually download the bootstrapper binary. On OpenShift, access the pod on the command line (rsh or terminal in web console) and run the following command:
```suggestion
To work around the problem, download the bootstrapper binary manually. On OpenShift, access the pod on the command line (shell or the terminal in the web console) and run the following commands:
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
>  cd /tmp/bootstrapper
```suggestion
$ cd /tmp/bootstrapper
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
>  ls -la  # to check if there's a bootstrapper binary
```suggestion
$ ls -la  <1>
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
>  curl ${CHE_URL}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
```suggestion
$ curl ${CHE_URL}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
>  ----
```suggestion
----
<1> to check for the existence of the bootstrapper binary
```

2018-11-22 11:24 UTC, rkratky commented on src/main/pages/workspace-admin/workspaces-troubleshooting.adoc
> +If this curl command fails, port `80` is blocked in your network or port `443` is blocked if you use `https` routes on OpenShift.
```suggestion
To prevent the `curl` command from failing, unblock port `80` on your network. On OpenShift with `https` routes, unblock port `443`.
```

2018-11-22 20:10 UTC, supriya-bharadwaj commented
Hi @rkratky , I just accepted all your suggestions. I think we can now merge this branch into master. Thanks!

2018-11-23 14:28 UTC, rkratky approved these changes

2018-11-23 14:28 UTC, merged