RHDEVDOCS-891: Reviewed the Workspace Data Model section for language…
eclipse-che/che-docs pull request #608
Opened 2018-11-23 13:57 UTC by supriya-bharadwaj

… and asciidoc syntax.

Signed-off-by: Supriya Takkhi <sbharadw@redhat.com>

### What does this PR do?
Fixes lang. and mark-up issues in *Workspace Data Model -> https://www.eclipse.org/che/docs/workspace-data-model.html*.
File name: `src/main/pages/workspace-admin/workspace-data-model.adoc`
Hi @rkratky , can you please review this PR? Thanks!

2018-11-23 15:30 UTC, rkratky requested changes

2018-11-23 15:30 UTC, rkratky commented on src/main/pages/workspace-admin/workspace-data-model.adoc
> +Environment recipe can also have content instead of location, if the link:recipes.html[recipe] type is `dockerfile`, `compose` or `openshift`:
serial comma
```suggestion
For link:recipes.html[recipe] types of `dockerfile`, `compose`, or `openshift`, content, not location, is specified.
```

2018-11-23 15:30 UTC, rkratky commented on src/main/pages/workspace-admin/workspace-data-model.adoc
> +If a project is misconfigured or missing sources, it is marked with an error code and a message explaining the error. In the example above, the project does not have errors and mixins.
if
```suggestion
Incorrectly configured projects or projects missing sources are marked with error codes and messages explaining the error. In the example above, the project does not have errors and mixins.
```

2018-11-23 15:30 UTC, rkratky commented on src/main/pages/workspace-admin/workspace-data-model.adoc
> +Runtime object is created when a workspace is in a running state. Runtime returns server URLs, internal or external, depending on the server configuration. Interested clients, like User Dashboard and
```suggestion
A runtime object is created when a workspace is in a running state. Runtime returns server URLs, internal or external, depending on the server configuration. Interested clients, like the *User Dashboard* and the IDE, use these URLs.
```

2018-11-23 15:45 UTC, supriya-bharadwaj commented
Hi @rkratky , I have accepted your suggestions. Can we merge this branch, please? Thanks!

2018-11-24 09:31 UTC, rkratky approved these changes

2018-11-24 09:31 UTC, merged