Added description how user-defined PVCs are processed on different PVC strategies
eclipse-che/che-docs pull request #657
Opened 2019-01-09 08:21 UTC by sleshchenko

### What does this PR do?
Adds description how user-defined PVCs are processed on different PVC strategies

### What issues does this PR fix or reference?
https://github.com/eclipse/che/pull/12335

2019-01-21 09:50 UTC, skabashnyuk commented
@dneary @slemeur @rkratky can you take a look on this PR?

2019-01-21 10:04 UTC, slemeur requested changes

2019-01-21 10:04 UTC, slemeur commented on src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
> +Che server, Keycloak and PostgreSQL pods, and workspace pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with https://kubernetes.io/docs/concepts/sto
"When the deployment YAML files run, they contain PVCs or define the Che Volumes."
I don't understand.
- Can a YAML file "run"
- they contain PVCs --> ?
- or define Che Volumes ???

2019-01-21 10:04 UTC, slemeur commented on src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
> +Every Che Volume of workspace gets its own PVC, which means a workspace PVCs are created when a workspace starts for the first time. Workspace PVCs are deleted when a corresponding workspace is delet
which means workspace PVCs 
remove "a"

2019-01-21 10:05 UTC, slemeur commented
Also do you confirm it is working the same for OS?

2019-01-28 14:26 UTC, sleshchenko commented on src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
> +Che server, Keycloak and PostgreSQL pods, and workspace pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with https://kubernetes.io/docs/concepts/sto
Good catch. I misunderstood this sentence. Now looks I should just revert my changes here. Will do it.

2019-01-28 14:29 UTC, sleshchenko commented on src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
> +Every Che Volume of workspace gets its own PVC, which means a workspace PVCs are created when a workspace starts for the first time. Workspace PVCs are deleted when a corresponding workspace is delet
done

2019-01-28 14:30 UTC, sleshchenko commented on src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
> +Che server, Keycloak and PostgreSQL pods, and workspace pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with https://kubernetes.io/docs/concepts/sto
Reverted changes in this line. Please resolve comment if existing line

> When the deployment YAML files run, they define the Che PVCs. You can configure link:#che-workspaces-storage[workspace PVC] access mode and claim size with Che deployment environment variables.

is OK for you.

2019-01-28 14:33 UTC, sleshchenko commented
> Also do you confirm it is working the same for OS?

Yes, it works for both of Kubernetes and OpenShift infrastructures. The modified page is included in `Che on Kubernetes: Admin Guide` and `Che on OpenShift: Admin Guide` articles.
@slemeur I fixed your comments, Could you please review one more time?

2019-04-03 06:15 UTC, slemeur approved these changes

2019-04-03 06:15 UTC, slemeur commented
@rkratky is that fine for you?

2019-07-23 07:03 UTC, slemeur commented
@rkratky : that PR has slipped while the content is making a great difference. I fixed the conflicts and going to merge, as there are explanation that would be much valuable for Che 7 (and CRW too).

2019-07-23 07:03 UTC, merged