Replace mentions of 'oAuth', by more accurate 'OAuth'. (See https://oauth.net/)
eclipse-che/che-docs pull request #745
Opened 2019-07-01 19:09 UTC by themr0c

2019-07-02 12:17 UTC, rkratky requested changes

2019-07-02 12:17 UTC, rkratky commented on src/main/pages/che-6/setup-docker/docker-single-user.adoc
> +Che CLI allows a wide range of configuration changes to set up the port, hostname, OAuth, Docker, git, and to solve networking issues. For details, see link:docker-config.html[Che configuration on Do
```suggestion
Che CLI supports configuring the port, hostname, OAuth, Docker, Git, and resolving networking issues. For details, see link:docker-config.html[Che configuration on Docker].
```

2019-07-02 18:53 UTC, themr0c commented
Merged in @rkratky suggestion and repushed to fix eclipsefdn/eca induced by edit from GitHub Web UI.

2019-07-03 13:54 UTC, rkratky approved these changes

2019-07-03 13:55 UTC, merged