Fixed duplication image and removed unnecessary image links
eclipse-che/che-docs pull request #773
Opened 2019-08-06 13:01 UTC by MichalMaler

https://issues.jboss.org/browse/RHDEVDOCS-1234?filter=12339718

Signed-off-by: Michal Maléř <mmaler@redhat.com>

"Pick a section (e.g. End-user Guide), go through all of its content, and fix screenshots. By fixing, I mean to make sure that big images are clickable links to themselves in orig. size, so they can be read. And small images (those that are not automatically resized in the browser) are not clickable so that it's not confusing."

2019-08-06 13:33 UTC, slemeur approved these changes

2019-08-07 21:06 UTC, rkratky requested changes

2019-08-07 21:06 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
> +image::che-6-workspace-confg.png[]
```suggestion
image::workspaces/che-6-workspace-confg.png[]
```

2019-08-07 21:06 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
> +image::che-6-workspace-confg.png[]
@MichalMaler The name of the image file should be fixed, too.

2019-08-07 21:06 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
> +image::workspaces/che-6-workspace-confg.png[]
Fix file name.

2019-08-07 21:06 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
> +image::workspaces/workspace_config_Che_6.png[]
No caps in file names.

2019-08-07 21:06 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
> +image::workspaces/che-6-workspace-confg.png[]
Fix file name.

2019-08-14 17:28 UTC, rkratky approved these changes

2019-08-14 17:28 UTC, merged