Add the missing dockerimage component endpoint attributes to the devfile reference
eclipse-che/che-docs pull request #797
Opened 2019-08-30 09:45 UTC by metlos

### What does this PR do?
`$TITLE`

### What issues does this PR fix or reference?
I've discovered this while investigating the docs for workspace exposure strategies (https://github.com/eclipse/che/issues/14189)

2019-08-30 09:57 UTC, skabashnyuk approved these changes

2019-08-30 20:33 UTC, rkratky requested changes

2019-08-30 20:33 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +* `path`: The URL path of the endpoint
```suggestion
* `path`: The URL of the endpoint
```

2019-08-30 20:33 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +* `secure`: A boolean (defaulting to `false`) specifying whether the endpoint will be put behind a JWT proxy requiring a JWT workspace token to grant access.
```suggestion
* `secure`: A boolean (defaulting to `false`) specifying whether the endpoint is put behind a JWT proxy requiring a JWT workspace token to grant access.
```

2019-08-30 20:33 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
> +* `cookieAuthEnabled`: If set to `true` (the default is `false`), the JWT workspace token will be automatically fetched and put to a workspace-specific cookie so that the JWT proxy let's the requests
```suggestion
* `cookieAuthEnabled`: When set to `true` (the default is `false`), the JWT workspace token is automatically fetched and included in a workspace-specific cookie to allow requests to pass through the JWT proxy.
+
WARNING: This setting potentially allows a link:https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF] attack when used in conjunction with a server using POST requests.

2019-08-30 20:33 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
>  If you start a new server within your component, Che will autodetect this and the UI will offer you to automatically expose this port as a `public` port. This is useful for debugging a web applicatio
```suggestion
When starting a new server within a component, Che autodetects this, and the UI offers to automatically expose this port as a `public` port. This is useful for debugging a web application, for example. It is not possible to do this for servers that autostart with the container (for example, a database server). For such components, specify the endpoints explicitly.
```

2019-09-03 10:43 UTC, rkratky approved these changes

2019-09-17 07:29 UTC, themr0c commented
Hi @metlos. The changes that you have committed from GitHub Web UI have been attributed to an email address that cannot be covered by necessary legal agreements (metlos@****.noreply). You should amend your commits to fix the email address in the commit. 
See: https://help.github.com/en/articles/changing-a-commit-message and https://help.github.com/en/articles/changing-author-info

2019-09-18 14:26 UTC, metlos commented
I've re-authored the commit and force pushed into the branch so that the license checks passs. Thanks for pointing out the problem to me @themr0c.

2019-09-18 14:29 UTC, merged

2019-09-18 14:30 UTC, themr0c commented
Thank you for the contribution, and thank you for your hard work fixing the license check.