Verifications after chectl installation
eclipse-che/che-docs pull request #806
Opened 2019-09-05 14:35 UTC by themr0c

Add verification steps after the installation of chectl 

fix eclipse/che/issues/14428

2019-09-05 14:35 UTC, themr0c commented
@benoitf please review!

2019-09-05 17:04 UTC, rkratky requested changes

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +$ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
Maybe use just `sh` to make it more universal?
```suggestion
$ sh <(curl -sL  https://www.eclipse.org/che/chectl/)
```

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +$ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
Ah, I see the script itself uses `bash`. Ok, disregard.

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
>  . Run the following commands in the terminal:
```suggestion
. Run the following command in the terminal (this downloads and executes the `install.sh` script):
```

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
>  . Run the following commands in the terminal:
The prereqs for this procedure should include the necessity to have the `sudo` command (environment) configured for the current user. (This isn't configured by default on RHEL, for example.)

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +The installation script requires superuser access.
The above comment about the `sudo` prereq should make this admonition redundant.

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +If necessary the user will be prompted for his password by sudo.
@themr0c, just a docs note: avoid 'if' and 'will' :)

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +. Run the following command to verify that the `chectl` binary that is used is `/usr/local/bin/chectl`:
```suggestion
. Run the following command to verify that the `chectl` binary used is `/usr/local/bin/chectl`:
```

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +[TIP]
This step should be before the installation of the right `chectl`:

1. (prereq) Remove all old or undesired versions of `chectl`
2. Run the install script
3. Verify that the install `chectl` is in your path

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +To determine the lates stable release navigate to the  link:https://github.com/che-incubator/chectl/releases[list of Chectl releases] and search for a release not containing "next" in her name.
```suggestion
To identify the latest stable release, see the link:https://github.com/che-incubator/chectl/releases[list of chectl releases] and search for a release not containing "next" in the name.
```

2019-09-05 17:04 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
> +cat chectl-install.log
```suggestion
$ cat chectl-install.log
```

2019-09-11 13:02 UTC, themr0c commented
Sorry I messed up with the GitHub web interface. As an unfortunate consequence I had to rebase, reset-author, squash and use the force. I believe all your concerns are adressed @rkratky.

2019-09-11 13:07 UTC, rkratky approved these changes

2019-09-11 13:07 UTC, merged

2019-09-11 13:07 UTC, themr0c commented
Thank you @rkratky !