Prepend /che/docs to search.json
eclipse-che/che-docs pull request #829
Opened 2019-09-26 15:21 UTC by danielhelfand

Signed-off-by: danielhelfand <helfand.4@gmail.com>

### What does this PR do?

#828 removed the stripping of the url from `search.json` as part of an effort to fix https://github.com/eclipse/che/issues/14647. While running locally with changes in #828 fixes the issue, it does not solve the problem for the che-docs site.

There appears to be a difference in how search works locally versus the site itself. The site requires /che/docs as part of the url while it does not locally.

This pull request prepends `/che/docs` in `search.json`. 

## Considerations

This change will mean that search will not work locally for the site. 

If there is a staging environment for the site, it would make sense to test there as opposed to verifying locally.

2019-09-26 15:51 UTC, danielhelfand commented
This does not appear to be the issue actually. I'll do some further digging.

2019-09-26 19:49 UTC, danielhelfand commented
In reviewing this, it does look like the issue seems to be related to `/che/docs` not being included with the base url. If you go to the site now, you'll get a request url of `https://www.eclipse.org/che-7/installing-che-on-openshift-4-from-operatorhub/` if searching for the OpenShift 4 installation doc. 

So it refers to `https://www.eclipse.org/` as the base url. If there's a more elegant way to change `site.baseurl`, please let me know, but I do believe this should address the search issue.

2019-09-26 23:35 UTC, rkratky requested changes
@danielhelfand, thanks for digging into this. When merging the #828 PR, I didn't realize it would affect the various environments differently.

We need `site.baseurl` to be `/` for local previews, `/che/docs/` for prod builds (because on eclipse.org, the docs are under `/docs/che/`, not in the webserver root), and finally `/docs/` for WAR builds (which is yet to be fixed; see https://github.com/eclipse/che/issues/14386).

I tested the solution I'm suggesting on both local and in a prod-like environment (you can do that by building with `run.sh -prod` and copying the contents of `_site/` to a `che/docs/` dir structure in your local web server's root). The clunky removal of the first `/` is needed because if we were to just prepend `site.baseurl`, the URL on local previews would start with `//`, which wouldn't work.

2019-09-26 23:35 UTC, rkratky commented on src/main/search.json
> +"url": "{{ page.url | prepend: '/che/docs' }}",
```suggestion
"url": "{{ page.url | remove_first: '/' | prepend: site.baseurl }}",
```

2019-09-26 23:35 UTC, rkratky commented on src/main/search.json
> +"url": "{{ post.url | prepend: '/che/docs' }}",
```suggestion
"url": "{{ page.url | remove_first: '/' | prepend: site.baseurl }}",
```

2019-09-27 13:52 UTC, danielhelfand commented
@rkratky Thanks for the detailed explanation and suggestions. I just pushed up a change, but let me know if there's anything else needed.

2019-09-27 18:46 UTC, rkratky approved these changes

2019-09-27 18:46 UTC, merged

2019-09-27 18:47 UTC, rkratky commented
Merged. Thanks for investigating this, @danielhelfand.

2019-09-27 19:11 UTC, danielhelfand commented
@rkratky Thanks! How soon will the changes be live?

2019-09-27 22:24 UTC, danielhelfand commented
Never mind, I see that it's published and looks to be working. Thanks again for the help.