FIXED the wrong link to Plugin registry, which is a duplicate to Devf…
eclipse-che/che-docs pull request #833
Opened 2019-09-30 14:37 UTC by bryantson

…ile registry.

### What does this PR do?
This corrects the wrong link explaining the Plugin Registry doc in Overview section. The Plugin Registry link was pointing to DevFile, which was possibly a duplicate mistake.

### What issues does this PR fix or reference?

2019-10-03 10:30 UTC, rkratky requested changes
@bryantson, thanks for your contribution. I suggested some changes. You'll also need to sign off your commits and sign the Eclipse Contributor Agreement, see https://www.eclipse.org/legal/ECA.php

2019-10-03 10:30 UTC, rkratky commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +| link:https://github.com/eclipse/che-plugin-registry[Che Plugin registry]
```suggestion
| link:https://github.com/eclipse/che-plugin-registry[Che Plug-in registry]
```

2019-10-03 10:30 UTC, rkratky commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +For more information about plug-in registry customization, see the [Customizing plug-in registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#cloning-the-plug
```suggestion
For more information about plug-in registry customization, see the link:{site-baseurl}che-7/building-and-running-a-custom-registry-image/[Customizing plug-in registry] section.
```

2019-10-03 10:30 UTC, rkratky commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +// ADDED "Customizing plug-in registry"
```suggestion
```

2019-10-06 04:36 UTC, bryantson commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +| link:https://github.com/eclipse/che-plugin-registry[Che Plugin registry]
Looks good to me.

2019-10-06 04:37 UTC, bryantson commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +// ADDED "Customizing plug-in registry"
Looks good to me.

2019-10-06 04:37 UTC, bryantson commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +For more information about plug-in registry customization, see the [Customizing plug-in registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#cloning-the-plug
Looks good to me.

2019-10-06 12:48 UTC, rkratky commented
@bryantson, the suggestions I provided did not actually change the PR. It's up to you to commit them (if you agree with them, which you appear to). Also, you will need to provide the sign offs for your commits.

2019-10-06 12:52 UTC, bryantson commented
I read the Eclipse Contribution Agreement, which is copied below, and full certify that I sign the agreement.

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file or
The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file or
The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.
I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my signoff) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

2019-10-06 12:54 UTC, bryantson commented
Merging is blocked. Is there any further action that I need to take, or can the reviewer merge?

2019-10-06 17:01 UTC, rkratky commented
@bryantson, the ECA needs to be "signed" on the eclipse.org website (refer to https://www.eclipse.org/legal/ECA.php). Before you can do it, you need to create an Eclipse account (use the same email address you use on GitHub).

After that, please, accept the suggestions provided in the comments. Then your commits need to be signed off on. I'll be happy to help with that once we get to that step.

2019-10-07 02:35 UTC, bryantson commented
@rkratky Signed :)

2019-10-07 08:39 UTC, themr0c approved these changes

2019-10-07 08:39 UTC, themr0c commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +For more information about plug-in registry customization, see the [Customizing plug-in registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#cloning-the-plug
This would be the right format for the link in asciidoc format:

```suggestion
For more information about plug-in registry customization, see the link:{site-baseurl}che-7/building-and-running-a-custom-registry-image/#cloning-the-plug-in-registry_cloning-the-registries[Customizing plug-in registry] section.
```

2019-10-07 08:43 UTC, themr0c commented
@bryantson it seems your signed commit didn't made it's way to GitHub?

2019-10-08 23:17 UTC, bryantson commented
@themr0c I don't think so at this point.

2019-10-17 07:35 UTC, themr0c commented on src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
> +For more information about plug-in registry customization, see the [Customizing plug-in registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#cloning-the-plug
@bryantson can you please apply this patch to fix the link?

2019-10-23 16:14 UTC, rkratky approved these changes

2019-10-23 16:16 UTC, rkratky commented
@bryantson, this still needs to have the commits signed off. Please, rebase, squash the commits, and add your sign-off line to the commit message.

2019-11-06 17:06 UTC, merged

2019-11-06 17:07 UTC, rkratky commented
Thanks, @bryantson. I fixed the ECA and sign off issues and merged your fix.