Explain the overrideCheProperties field
eclipse-che/che-docs pull request #838
Opened 2019-10-03 20:15 UTC by tomgeorge

### What does this PR do?

Explains the new `overrideCheProperties` field in the `CheCluster` Custom Resource and shows an example CR that has an additional property.

### What issues does this PR fix or reference?
eclipse/che#14166

2019-10-04 04:15 UTC, tomgeorge commented
I think we are going to change the field name in the `CheCluster` cr, so these docs will need to change.

2019-10-04 07:56 UTC, davidfestal commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> -* The `che` `configMap` contains the main properties for the installation and is in sync with the information stored in the CheCluster Custom Resource file. User modifications of the `che` `configMap
I would replace:

*main properties __for the installation__*

by 

*main properties __for the Che server__*

2019-10-04 08:03 UTC, davidfestal requested changes
Please look at my comments

2019-10-04 08:03 UTC, davidfestal commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +To add custom properties, such as environment variables that are not created by the `che` `configMap` by default, or to override standard properties, the `CheCluster` Custom Resource has a `overrideC
```suggestion
To add custom properties to the Che server, such as environment variables that are not automatically generated in the `che` `configMap` by the operator, or to override automatically generated properties, the `CheCluster` Custom Resource has a `customCheProperties` field, that expects a map.  
```

2019-10-04 08:03 UTC, davidfestal commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +For example, to add a property named `FOO` with value `BAR`, add an entry in `overrideCheProperties`:
```suggestion
For example, to add a property named `FOO` with value `BAR`, add an entry in `customCheProperties`:
```

2019-10-04 08:03 UTC, davidfestal commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +Previous versions of the Che operator had a configMap named `custom` to fulfill this role.  If the Che operator finds a `configMap` with the name `custom`, it will add the data it contains to the `ov
```suggestion
Previous versions of the Che operator had a configMap named `custom` to fulfill this role.  If the Che operator finds a `configMap` with the name `custom`, it will add the data it contains into the `customCheProperties` field, redeploy Che, and delete the `custom` `configMap`. 
```

2019-10-04 08:58 UTC, rkratky requested changes

2019-10-04 08:58 UTC, rkratky commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +Che installed using the Operator provides the user with an automatically generated `che` `configMap`.
```suggestion
Che installed using the Operator provides the user with an automatically generated `configMap` called `che`.
```

2019-10-04 08:58 UTC, rkratky commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +The `che` `configMap` contains the main properties for the installation and is in sync with the information stored in the CheCluster Custom Resource file. User modifications of the `che` `configMap`
```suggestion
The `che` `configMap` contains the main properties for the Che server and is in sync with the information stored in the CheCluster Custom Resource file. User modifications of the `che` `configMap` after installing Che using the Operator are automatically overwritten by values that the Operator obtains from the `CheCluster` Custom Resource. 
```

2019-10-04 08:58 UTC, rkratky commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +To add custom properties, such as environment variables that are not created by the `che` `configMap` by default, or to override standard properties, the `CheCluster` Custom Resource has a `overrideC
Building on David's suggestion:

```suggestion
To add custom properties to the Che server, such as environment variables that are not automatically generated in the `che` `configMap` by the Operator, or to override automatically generated properties, the `CheCluster` Custom Resource has a `customCheProperties` field, which expects a map.  
```

2019-10-04 08:58 UTC, rkratky commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +Previous versions of the Che operator had a configMap named `custom` to fulfill this role.  If the Che operator finds a `configMap` with the name `custom`, it will add the data it contains to the `ov
Building on David's suggestion:

```suggestion
Previous versions of the Che Operator had a configMap named `custom` to fulfill this role.  If the Che Operator finds a `configMap` with the name `custom`, it adds the data it contains into the `customCheProperties` field, redeploys Che, and deletes the `custom` `configMap`. 
```

2019-10-04 14:22 UTC, tomgeorge commented
@rkratky @davidfestal I made the changes that you suggested.

2019-10-04 17:47 UTC, davidfestal requested changes

2019-10-04 17:47 UTC, davidfestal commented on src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
> +    externalDb: false
I'm not sure we need to add all the other fields in the other sections...
Maybe ... would be sufficient no ?

2019-10-04 18:04 UTC, tomgeorge commented
@rkratky we are ready with https://github.com/eclipse/che-operator/pull/87.  Once this is approved we will merge

2019-10-04 18:25 UTC, davidfestal approved these changes
All is OK on my side.
Let's just wait for docs team approval before merging the main PR.

2019-10-04 18:36 UTC, nickboldt requested changes
Instead of `FOO: BAR` why not include some (or all) of the image and pull_policy references in che.properties, so we have an example of WHY you'd use this override mechanism?

eg. for productization and using chectl to deploy CRW:

`CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE: 'registry.redhat.io/codeready-workspace/jwtproxy-rhel8:2.0'`

and for airgap:
`CHE_FACTORY_DEFAULT__PLUGINS: 'myquay.mycorp.com/che-machine-exec-plugin/7.2.7'`
`CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: 'Never'`

I would also link to https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties and explicitly explain how those properties map to fields in a yaml file: 

* uppercase the parameter
* replace `.` with `_` and `_` with `__`

Thus:

`che.workspace.plugin_broker.pull_policy` -> `CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY`

2019-10-04 19:02 UTC, davidfestal commented
> I would also link to https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties and explicitly explain how those properties map to fields in a yaml file:
> 
>     * uppercase the parameter
> 
>     * replace `.` with `_` and `_` with `__`
> 
> 
> Thus:
> 
> `che.workspace.plugin_broker.pull_policy` -> `CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY`

Seems to me that this is more related to a different docs issue:

https://github.com/eclipse/che/issues/13886#issuecomment-534171945

I'd rather not block the merge of PR https://github.com/eclipse/che/issues/14635 for this.

2019-10-04 20:04 UTC, davidfestal commented
> eg. for productization and using chectl to deploy CRW:
> 
> `CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE: 'registry.redhat.io/codeready-workspace/jwtproxy-rhel8:2.0'`
> 
> and for airgap:
> `CHE_FACTORY_DEFAULT__PLUGINS: 'myquay.mycorp.com/che-machine-exec-plugin/7.2.7'`
> `CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: 'Never'`

Maybe I would keep the air-gap aspect for this other Che docs PR : https://github.com/eclipse/che/issues/14088#issuecomment-534174598

2019-10-04 20:19 UTC, nickboldt submitted a review, later dismissed
Ok, @davidfestal those other issues can cover the doc issues. 

But I'd still rather see a real(ish) example than `FOO:BAR` like 

`CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE: 'registry.redhat.io/codeready-workspace/jwtproxy-rhel8:2.0'`

2019-10-06 16:39 UTC, rkratky approved these changes

2019-10-07 08:36 UTC, themr0c approved these changes

2019-10-07 08:38 UTC, merged

2019-10-07 08:42 UTC, davidfestal commented
@themr0c why did you merge this already ? Shouldn't we wait for the corresponding main PR to be merged to master and, even more, released to production with the 7.3.0 release ?

2019-10-07 08:46 UTC, themr0c commented
How should I have known?

2019-10-07 08:48 UTC, davidfestal commented
> How should I have known?

I thought it was the usual way: only merge a doc change when the related product change is released.
But I should have been clearer in the PR description it seems.

2019-10-07 08:52 UTC, themr0c commented
Yes please prepend "[WIP]" to the title of your PR when it should not me merged, and remove it once it can be merged.

It's first time we are ahead of the product, documentation is usually lagging behind, so I didn't even thought about verifying the feature is present!