Update che4z-release-information.adoc
eclipse-che/che-docs pull request #849
Opened 2019-10-16 12:18 UTC by DStatWriter

Update release notes for 0.8.2 and 0.8.3

Signed-off-by: Daniel Statham <Daniel.statham@broadcom.com>

### What does this PR do?
Updates release notes for LSP for Cobol

### What issues does this PR fix or reference?
#14903

2019-10-16 13:31 UTC, rkratky requested changes

2019-10-16 13:31 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +--- Version 0.8.3
```suggestion
=== Version 0.8.3
```

2019-10-16 13:31 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +* Java automatic check fixed to recognize all supported JRE/JDK java implementations.
```suggestion
* Java automatic check fixed to recognize all supported JRE and JDK implementations.
```

2019-10-16 13:31 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +--- Version 0.8.2
```suggestion
=== Version 0.8.2
```

2019-10-16 13:31 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +* README Updated
```suggestion
* README updated
```

2019-10-24 11:52 UTC, themr0c commented
This still needs to have the commits signed off. Please, rebase, squash the commits, add your sign-off line to the commit message, and push --force.

2019-11-05 09:32 UTC, closed without merging

2019-11-05 09:33 UTC, DStatWriter commented
Closed for resubmission