Add Configuring GitHub OAuth section
eclipse-che/che-docs pull request #862
Opened 2019-10-23 11:43 UTC by vinokurig

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
Add Configuring GitHub OAuth section

### What issues does this PR fix or reference?
https://github.com/eclipse/che-theia/pull/497

2019-10-23 16:12 UTC, rkratky requested changes
Thanks, @vinokurig. I added some suggestions.

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +== Configuring GitHub OAuth
```suggestion
= Configuring GitHub OAuth
```

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +OAuth for Github allows users to import projects using SSH addresses (`git@`), push to repositories, and use the *Pull Request* panel. To enable automatic SSH key upload to GitHub for users:
```suggestion
OAuth for Github allows users to import projects using SSH addresses (`git@`), push to repositories, and use the *Pull Request* panel.
```

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +. On *github.com*, click your user icon (top right).
```suggestion
.Procedure

To enable automatic SSH key upload to GitHub for users:

. On *github.com*, click your user icon (top right).
```

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +. On OpenShift/Kubernetes, update the deployment configuration (see link:openshift-config.html[OpenShift configuration]).
```suggestion
. On OpenShift or Kubernetes, update the deployment configuration (see link:https://www.eclipse.org/che/docs/che-6/openshift-config.html[OpenShift configuration]).
```

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +
```suggestion
endif::[]

```

2019-10-23 16:12 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
> +====
```suggestion
endif::[]
====
```

2019-10-24 07:28 UTC, rkratky approved these changes

2019-10-24 07:31 UTC, vinokurig commented
@rkratky I've removed the `Pull request panel` it was added mistakenly

2019-10-24 07:33 UTC, rkratky commented
> I've removed the Pull request panel it was added mistakenly

Oops, sorry, I misunderstood. Thanks.

Please, merge when ready.

2019-10-24 07:47 UTC, merged