Update che4z-installing.adoc
eclipse-che/che-docs pull request #867
Opened 2019-10-23 15:29 UTC by DStatWriter

Signed-off-by: Daniel Statham <daniel.statham@broadcom.com>

### What does this PR do?
Expands on the install section, removing the need for users to click through to another page

### What issues does this PR fix or reference?
#14967 #14981

2019-10-23 16:01 UTC, rkratky requested changes

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +=== Prerequisites
```suggestion
.Prerequisites
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +'''
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +=== Installation
```suggestion
.Procedure
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +===== *Follow these steps:*
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +. Install Eclipse Che by running the following command, and replacing <DATA_FOLDER> with the location of user data on the host machine:
```suggestion
. Install Eclipse Che by running the following command. Replace `__<DATA_FOLDER>__` with the location of user data on the host machine:
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +----
```suggestion
+
[subs="+quotes"]
----
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +	docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=`hostname -f` -e
```suggestion
$ docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=`hostname -f` -e \
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +	CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock -v
```suggestion
  CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock -v \
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +	/var/run/docker.sock:/var/run/docker.sock -v /<DATA_FOLDER>:/data eclipse/che:7.0.0-beta-4.0 start
```suggestion
  /var/run/docker.sock:/var/run/docker.sock -v /__<DATA_FOLDER>__:/data eclipse/che:7.0.0-beta-4.0 start
```
Is it really dependent on Che v7.0.0-beta-4.0? If not, suggest using a placeholder for the latest version.

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +- For more information on configuring Eclipse Che with Docker, see https://www.eclipse.org/che/docs/che-6/docker-multi-user.html[here]
```suggestion
+
For more information on configuring Eclipse Che with Docker, see https://www.eclipse.org/che/docs/che-6/docker-multi-user.html[Installation on Docker].
```
Perhaps we should be pointing to Che 7 docs and local installation methods?

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +. Log in to Che using the default administrator account:
```suggestion
. Log in to Che using the default administrator account (username = `admin`, password = `admin`).
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +  - (username = admin, password = admin).
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +. (Optional) Configure the Keycloak security server by following the instructions https://www.eclipse.org/che/docs/che-6/user-management.html#che-and-keycloak[here].
```suggestion
. (Optional) Configure the Keycloak security server by following the instructions https://www.eclipse.org/che/docs/che-6/user-management.html#che-and-keycloak[Managing users].
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +. Run *start_installer.sh* (on Linux) or *start_installer.cmd* (on Windows).
```suggestion
. Run `start_installer.sh` (on Linux) or `start_installer.cmd` (on Windows).
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +You installed Eclipse Che and the Che4z extensions.
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +'''
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +=== Creating a Workspace
```suggestion
== Creating a workspace
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +===== *Follow these steps:*
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +1. Log in to Che. Use your credentials, or the default administrator account credentials:
```suggestion
. Log in to Che. Use your credentials or the default administrator account (username = `admin`, password = `admin`).
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +  - (username = admin, password = admin).
```suggestion
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +2. To create a new workspace, select *Workspaces - Add Workspace*.
```suggestion
. Select *Workspaces -> Add Workspace*.
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +3. In *Select Stack*, select *view all*, then choose *Broadcom Mainframe* stack.
```suggestion
. In *Select Stack*, select *view all*, then choose the *Broadcom Mainframe* stack.
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +4. Create and open the workspace.
```suggestion
. Create and open the workspace.
```

2019-10-23 16:01 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-installing.adoc
> +You created a workspace and can now use the Eclipse Che4z extensions.
```suggestion
A workspace has been created that can use the Eclipse Che4z extensions.
```

2019-10-23 16:03 UTC, rkratky requested changes
Thanks, @DStatWriter. I added some suggestions.

2019-10-24 11:53 UTC, themr0c commented
this still needs to have the commits signed off. Please, rebase, squash the commits, and add your sign-off line to the commit message.

2019-10-24 12:49 UTC, DStatWriter commented
> this still needs to have the commits signed off. Please, rebase, squash the commits, and add your sign-off line to the commit message.



> this still needs to have the commits signed off. Please, rebase, squash the commits, and add your sign-off line to the commit message.

Hey Fabrice, I did with the original submit, but it has to be added to each individual commit created by accepting change suggestions? I guess im best just re-submitting the changed ersion fresh with a single sign off, which i think is what you might have been suggesting here.

Dan

2019-10-24 12:51 UTC, themr0c commented
@DStatWriter Yes, that's exactly what I meant!

2019-10-24 12:53 UTC, DStatWriter commented
> @DStatWriter Yes, that's exactly what I meant!

Ok great, thanks

Dan

2019-10-24 13:10 UTC, themr0c commented
@DStatWriter and don't forget to look also at the suggestions that are in the "14 hidden conversations".

2019-10-24 13:15 UTC, themr0c commented
(and then again the same amend signoff squash and push force of course)

2019-10-25 08:53 UTC, DStatWriter commented
Re-validated PR with corrected email

2019-10-25 08:54 UTC, closed without merging