Upgrade che with cli
eclipse-che/che-docs pull request #931
Opened 2019-11-20 20:37 UTC by themr0c

* Refactoring installation procedures on OpenShift 3.
* Adding upgrade procedures using the CLI on OpenShift 3 and 4.

2019-11-22 12:52 UTC, rkratky requested changes

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
> +WARNING: The method that was used to install the {prod-short} {prod-prev-ver} instance determines the method to proceed to the upgrade.
```suggestion
WARNING: The method that was used to install the {prod-short} {prod-prev-ver} instance determines the method to proceed with for the upgrade.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
> +* xref:upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool_{context}[]
The `prod-short` and `prod-ver` attribute names shouldn't be in the IDs.

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
> +include::proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc[leveloffset=+1]
The prod-short and prod-ver attribute names shouldn't be in the file names.

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +[id="upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool_{context}"]
The prod-short and prod-ver attribute names shouldn't be in the IDs.

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +* A running instance of {prod} runninng on OpenShift 3.
```suggestion
* A running instance of {prod} running on OpenShift 3.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +* `chectl` management tool is installed. See link:{site-baseurl}che-7/installing-the-chectl-management-tool/[Installing the `chectl` management tool].
```suggestion
* The `chectl` management tool is installed. See link:{site-baseurl}che-7/installing-the-chectl-management-tool/[Installing the `chectl` management tool].
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the git repositories.
```suggestion
. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the Git repositories.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +. Run following command:
```suggestion
. Run the following command:
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +chectl server:update
```suggestion
$ chectl server:update
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc
> +. Login into the {prod-short} instance.
```suggestion
. Log in to the {prod-short} instance.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc
> +* A running instance of {prod} runninng on OpenShift 4.
```suggestion
* A running instance of {prod} running on OpenShift 4.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc
> +* `chectl` management tool is installed. See link:{site-baseurl}che-7/installing-the-chectl-management-tool/[Installing the `chectl` management tool].
```suggestion
* The `chectl` management tool is installed. See link:{site-baseurl}che-7/installing-the-chectl-management-tool/[Installing the `chectl` management tool].
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc
> +. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the git repositories.
```suggestion
. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the Git repositories.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc
> +chectl server:update
```suggestion
$ chectl server:update
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/installation-guide/proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc
> +. Login into the {prod-short} instance.
```suggestion
. Log in to the {prod-short} instance.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
> +. The previous command output end with:
```suggestion
. The output of the previous command ends with:
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
> +. Navigate to the {prod-short} cluster instance. The domain is now prefixed with HTTPS and using _Let’s Encrypt_ ACME certificates: `https:/che-che.<OPENSHIFT_APPS_URL>`.
```suggestion
. Navigate to the {prod-short} cluster instance. The domain is now prefixed with HTTPS and using _Let’s Encrypt_ ACME certificates: `++https://++che-che.__<OPENSHIFT_APPS_URL>__`.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
> +* The `oc` OpenShift 3.11 CLI management tool is installed and configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/cli-reference-ge
I think we should link to docs.openshift.com

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
> +* The `oc` OpenShift 3.11 CLI management tool is installed and configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/cli-reference-ge
I think we should link to docs.openshift.com

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
> +$ chectl server:start --platform=openshift --installer=operator --domain=<OPENSHIFT_APPS_URL>
```suggestion
$ chectl server:start --platform=openshift --installer=operator \
  --domain=__<OPENSHIFT_APPS_URL>__
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
> +. The previous command output end with:
```suggestion
. The output of the previous command ends with:
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
> +. Navigate to the {prod-short} cluster instance: `http:/che-che.<OPENSHIFT_APPS_URL>`.
```suggestion
. Navigate to the {prod-short} cluster instance: `++http://++che-che.__<OPENSHIFT_APPS_URL>__`.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
> +* The `oc` OpenShift 3.11 CLI management tool is installed and configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/cli-reference-ge
I think we should link to docs.openshift.com

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
> +. Run following command to verify the version of the `oc` OpenShift CLI management tool is 3.11.
```suggestion
. Run the following command to verify that the version of the `oc` OpenShift CLI management tool is 3.11:
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
> +. Run following commands to create a dummy project to find the URL that this OpenShift instance is using to deploy applications.
```suggestion
. Run the following commands to create a dummy project to find the URL that this OpenShift instance is using to deploy applications.
```

2019-11-22 12:52 UTC, rkratky commented on src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
> +. Extract the domain from `++httpd-ex-hello-world.apps.rhpds311.openshift.opentlc.com++`. It is the part after the first name: `apps.rhpds311.openshift.opentlc.com`. Remember this URL as `<OPENSHIFT_
```suggestion
. Extract the domain from `++httpd-ex-hello-world.apps.rhpds311.openshift.opentlc.com++`. It is the part after the first name: `apps.rhpds311.openshift.opentlc.com`. Remember this URL as `__<OPENSHIFT_APPS_URL>__`.
```

2019-11-24 18:45 UTC, rkratky commented
@themr0c, I submitted https://github.com/themr0c/che-docs/pull/1 against your topic branch. It should fix all the comments above. Please, let me know if it works for you.

2019-11-25 10:20 UTC, themr0c commented
@rkratky I integrated your PR and some other fixes.

2019-11-25 12:55 UTC, rkratky approved these changes

2019-11-25 12:55 UTC, merged