Update che4z-release-information.adoc
eclipse-che/che-docs pull request #938
Opened 2019-11-22 15:24 UTC by DStatWriter

Updated and Expanded Che4z Release info

Signed-off-by: Daniel Statham <Daniel.Statham@Broadcom.com>

### What does this PR do?
Expands and updates Che4z Release Notes

### What issues does this PR fix or reference?
#15288

2019-11-22 16:25 UTC, rkratky requested changes

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +----
```suggestion
---
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +----
```suggestion
---
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> += Che4z Release Information
We don't use title case for headings in Che docs.
```suggestion
= Che4z release information
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +* Java automatic check fixed to recognize all supported JRE/JDK java implementations.
```suggestion
* Java automatic check fixed to recognize all supported JRE and JDK implementations.
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +=== Release notes - COBOL Language Support
```suggestion
== Release notes - COBOL Language Support
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +==== Version 0.8.3
```suggestion
=== Version 0.8.3
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +==== Version 0.81
```suggestion
=== Version 0.81
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +==== Version 0.8
```suggestion
=== Version 0.8
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +=== Release notes - Explorer for Endevor
```suggestion
== Release notes - Explorer for Endevor
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +==== Version 0.8.0
```suggestion
=== Version 0.8.0

```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +Version 0.8 was released on 1 August 2019 and includes the following features:
```suggestion
Version 0.8 was released on 1 August 2019 and included the following features:
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +==== Version 0.9.0
```suggestion
=== Version 0.9.0
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +- Explorer for Endevor lets you create customer filters based on the searches you perform in the Map View
```suggestion
- Explorer for Endevor lets you create customer filters based on the searches you perform in the Map View.
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +- Explorer for Endevor lets you browse through Endevor data without any prior knowledge of the file paths being necessary
```suggestion
- Explorer for Endevor lets you browse through Endevor data without any prior knowledge of the file paths being necessary.
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +Version 0.9 was released on 19 September 2019 and includes the following features:
```suggestion
Version 0.9 was released on 19 September 2019 and included the following features:
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +- Experienced users can create custom filters without having to use Map View
```suggestion
- Experienced users can create custom filters without having to use Map View.
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +- Streamlined process to create new Host connections
```suggestion
- Streamlined process to create new Host connections.
```

2019-11-22 16:25 UTC, rkratky commented on src/main/pages/che-7/extensions/che4z-release-information.adoc
> +- link:https://docs.zowe.org/stable/[Zowe CLI and Plugin Documentation]
```suggestion

- link:https://docs.zowe.org/stable/[Zowe CLI and Plugin Documentation]
```

2019-11-25 07:43 UTC, DStatWriter commented
Requested changes applied as single commit. Please re-review and merge if satisfied.

Thanks, Dan

2019-11-25 09:12 UTC, rkratky approved these changes

2019-11-25 09:12 UTC, merged