Paragraph about how the network must allow traffic from inside the cl…
eclipse-che/che-docs pull request #944
Opened 2019-11-25 16:04 UTC by tomgeorge

### What does this PR do?
Documents the requirement of traffic from outside the cluster to be able to reach Route/Ingress hostnames

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15308
https://github.com/eclipse/che/issues/15187

2019-11-25 16:40 UTC, rkratky requested changes
Thanks, @tomgeorge. I left a couple of suggestions.

2019-11-25 16:40 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
> +== Prerequesite Notes on Network Connectivity
```suggestion
== Notes on network connectivity in restricted environments
```

2019-11-25 16:40 UTC, rkratky commented on src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
> +Restricted network environments can range from a private subnet in a cloud provider, to a separate network owned by a company, cut off from the public internet.  While your organization's network wil
```suggestion
Restricted network environments range from a private subnet in a cloud provider to a separate network owned by a company, disconnected from the public Internet. Regardless of the network configuration, {prod-short} works *provided that the Ingress and Routes that are created for {prod-short} components ({prod-id-short}-server, keycloak, devfile-registry, plugin-registry) are accessible from inside the Kubernetes or OpenShift cluster).*

Take into account the network topology of the environment to determine how best to accomplish this. For example, on a network owned by a company or an organization, the network administrators must ensure that traffic bound from the cluster can be routed to Ingress and Route hostnames. In other cases, for example, on AWS, create a proxy configuration allowing the traffic to leave the node to reach an external-facing Load Balancer.
```

2019-11-25 19:56 UTC, tomgeorge commented on src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
> +Restricted network environments can range from a private subnet in a cloud provider, to a separate network owned by a company, cut off from the public internet.  While your organization's network wil
I have updated based on your suggestions

2019-11-26 08:11 UTC, ibuziuk approved these changes

2019-11-26 10:58 UTC, rkratky approved these changes

2019-11-26 10:59 UTC, merged