Add devfile parameters override procedure
eclipse-che/che-docs pull request #952
Opened 2019-11-29 12:13 UTC by mshaposhnik

### What does this PR do?
Added proc for overriding devfile parameters via factory URL prameters.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13617

2019-11-29 13:09 UTC, rkratky requested changes

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> += Overriding some devfile values using factory parameters
```suggestion
= Overriding devfile values using factory parameters
```

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> +// overriding-devfile-values-using-factory-parameters
```suggestion
// included in:
//
// * assembly_configuring-a-workspace-using-a-devfile.adoc
```

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> +A some values of the remote devfile can be overriden using specially constructed additional factory parameters. Currently allowed sections to override values are: apiVesion, metadata, projects.
```suggestion
Values in the following sections of a remote devfile can be overridden using specially constructed additional factory parameters:

* `apiVersion`
* `metadata`
* `projects`
```

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> +* The publicly-accessible standalone `devfile.yaml` file. See link:{site-baseurl}che-7//making-a-workspace-portable-using-a-devfile/[Making a workspace portable using a Devfile] for detailed informat
```suggestion
* A publicly accessible standalone `devfile.yaml` file. See link:{site-baseurl}che-7//making-a-workspace-portable-using-a-devfile/[Making a workspace portable using a Devfile] for detailed information about creating and using devfiles.
```

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> +. Execute the workspace by opening the following URL: `++https://++__<your-che-host>__/f?url=https://__<yourhosturl>__/devfile.yaml&override.<parameter.path>=<value>`
```suggestion
. Open the workspace by navigating to the following URL: `++https://++__<che-host>__/f?url=https://__<hostURL>__/devfile.yaml&override.__<parameter.path>__=__<value>__`
```

2019-11-29 13:09 UTC, rkratky commented on src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
> +.Example of overriding generateName property
```suggestion
.Example of overriding the `generateName` property
```

2019-12-02 12:01 UTC, mshaposhnik commented
@rkratky Please take a look if that's looks good now, thanks.

2019-12-02 13:44 UTC, rkratky approved these changes
Thanks, @mshaposhnik

2019-12-02 13:44 UTC, merged